"use strict";
/* Tài khoản cloud: cookie HttpOnly; lưu máy trước, đồng bộ cả ba ô và kho nguyên tử. */
const CLOUD_SHARED=['stash','clan','guild','collections'].flatMap(name=>['','_ctc','_phlt'].map(s=>'jxidle_'+name+s));
const CLOUD={user:null,meta:null,revision:0,ready:false,lease:false,paused:false,busy:false,status:'Chưa đăng nhập',lastSaved:0,lastLeaseAt:0,preview:null,detachedBundle:null};
const CLOUD_SYNC_MS=30000;
let cloudEntryPending=true;try{cloudEntryPending=sessionStorage.getItem('jxidle_cloud_guest_entry')!=='1'}catch(e){}
let cloudAuthGeneration=0;
const CLOUD_BINDING='jxidle_cloud_binding',CLOUD_OWNER='jxidle_cloud_owner';
let cloudLoadedOwner='guest';try{cloudLoadedOwner=localStorage.getItem(CLOUD_OWNER)||'guest'}catch(e){}
let cloudClientId;
try{cloudClientId=sessionStorage.getItem('jxidle_cloud_device')}catch(e){}
if(!cloudClientId){cloudClientId=Array.from(crypto.getRandomValues(new Uint8Array(18)),n=>n.toString(16).padStart(2,'0')).join('');try{sessionStorage.setItem('jxidle_cloud_device',cloudClientId)}catch(e){}}
function cloudLocal(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch(e){return null}}
function cloudPut(key,value){localStorage.setItem(key,JSON.stringify(value))}
function cloudRootKeys(){return Array.from({length:3},(_,i)=>[slotKey(i),slotKey(i)+'_bak',slotKey(i)+'_m',slotKey(i)+'_kps',slotKey(i)+'_online']).flat().concat(CLOUD_SHARED,CLOUD_SHARED.map(k=>k+'_bak'),[SLOT_PTR]);}
function cloudClean(value){if(Array.isArray(value))return value.map(cloudClean);if(value&&typeof value==='object'){const out={};for(const [key,v]of Object.entries(value)){if(['__proto__','constructor','prototype','token','password','secret','authorization','sandbox','admin'].includes(key.toLowerCase()))continue;out[key]=cloudClean(v);}return out;}return value;}
function cloudCapture(persist=true){if(CLOUD.detachedBundle){const saved=JSON.parse(JSON.stringify(CLOUD.detachedBundle));if(S&&S.fac){const state=cloudClean(S);delete state.snd;saved.slots[SLOT]=state;}return saved;}if(typeof ADMV!=='undefined'&&ADMV.sandbox)throw new Error('Thoát chế độ thử nghiệm trước khi đồng bộ');if(persist&&S&&S.fac&&!SAVE_LOCK)save();const slots=Array.from({length:3},(_,i)=>{const raw=localStorage.getItem(slotKey(i));if(!raw)return null;const u=unpack(raw);if(!u.ok)throw new Error('Ô '+(i+1)+' có dữ liệu lỗi; cần khôi phục bản lưu trước');if(!u.state.fac)return null;const state=cloudClean(u.state);state.mode=stateMode(state)||'g2';delete state.snd;return state;});if(S&&S.fac&&SAVE_LOCK){const live=cloudClean(S);delete live.snd;slots[SLOT]=live;}const shared={};for(const key of CLOUD_SHARED){const raw=localStorage.getItem(key);if(raw){const u=unpack(raw);if(!u.ok)throw new Error('Dữ liệu kho hoặc bộ sưu tập bị lỗi');shared[key]=cloudClean(u.state);}}return {v:1,slots,shared};}
function cloudFingerprint(bundle){const copy=JSON.parse(JSON.stringify(bundle));for(const s of copy.slots)if(s){delete s.last;delete s.bakAt;}return sigOf(JSON.stringify(copy));}
function cloudArchive(){if(S&&S.fac&&!SAVE_LOCK)save();const raw={};for(const key of cloudRootKeys())raw[key]=localStorage.getItem(key);const owner=localStorage.getItem(CLOUD_OWNER)||'guest';cloudPut('jxidle_cloud_archive_'+owner,{raw,bundle:cloudCapture(false),at:Date.now()});return raw;}
function cloudSaveBinding(fingerprint){cloudPut(CLOUD_BINDING,{id:CLOUD.user.id,username:CLOUD.user.username,revision:CLOUD.revision,fingerprint,lastSaved:CLOUD.lastSaved});localStorage.setItem(CLOUD_OWNER,CLOUD.user.id);cloudLoadedOwner=CLOUD.user.id;localStorage.setItem('jxidle_cloud_tab',cloudClientId);}
function cloudStatus(text){CLOUD.status=text;const b=document.getElementById('jxCloud');if(b)b.title='Tài khoản · '+text;const el=document.getElementById('cloudState');if(el)el.textContent=text;}
async function cloudApi(path,body){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
  const opts={credentials:'same-origin',cache:'no-store',signal:controller.signal};
  if(body!==undefined){opts.method='POST';opts.headers={'content-type':'application/json'};opts.body=JSON.stringify(body);}
  try{const r=await fetch('/api/cloud/'+path,opts);const data=await r.json();if(!r.ok){const e=new Error(data.msg||'Máy chủ chưa hỗ trợ tài khoản ('+r.status+')');e.code=data.error||'http';throw e;}return data;}
  catch(e){if(e.code)throw e;const error=new Error(e.name==='AbortError'?'Máy chủ phản hồi quá lâu. Hãy thử lại.':'Không kết nối được máy chủ · tiến trình vẫn lưu tại máy');error.code='offline';throw error;}
  finally{clearTimeout(timer);}
}
function cloudFail(e){cloudStatus(e.message);if(['save_conflict','device_changed','device_busy','cloud_login','cloud_disabled','market_restore'].includes(e.code)){CLOUD.paused=true;CLOUD.lease=false;}if(e.code==='cloud_login'){CLOUD.ready=false;CLOUD.user=null;if(window.accountAdminRefresh)window.accountAdminRefresh();}if(e.code==='device_busy'&&localStorage.getItem('jxidle_cloud_tab')!==cloudClientId&&!CLOUD.detachedBundle){try{CLOUD.detachedBundle=cloudCapture(false);sessionStorage.setItem('jxidle_cloud_unsaved',JSON.stringify({owner:cloudLoadedOwner,bundle:CLOUD.detachedBundle}));}catch(error){}SAVE_LOCK=true;document.getElementById('app').inert=true;setTimeout(cloudAccountMenu,0);}}
function cloudDeviceName(){return /iPhone|iPad/.test(navigator.userAgent)?'iPhone / iPad':/Android/.test(navigator.userAgent)?'Điện thoại Android':'Máy tính / trình duyệt';}
async function cloudClaim(takeover=false){const r=await cloudApi('claim',{clientId:cloudClientId,device:cloudDeviceName(),takeover});CLOUD.lease=true;CLOUD.lastLeaseAt=Date.now();CLOUD.meta=r;if(localStorage.getItem(CLOUD_OWNER)===CLOUD.user.id)localStorage.setItem('jxidle_cloud_tab',cloudClientId);return r;}
async function cloudLinkPvp(){const links=[];for(let i=0;i<3;i++){const raw=localStorage.getItem(slotKey(i)+'_online');if(!raw)continue;try{const account=JSON.parse(raw),state=cloudCapture(false).slots[i];if(account.token&&isMode(state?.mode)&&state?.online?.id===account.id)links.push({slot:i,token:account.token});}catch(e){}}
if(links.length)try{await cloudApi('link-pvp',{links})}catch(e){cloudStatus('Đã lưu · chưa liên kết PvP: '+e.message);}}
async function cloudSync(force=false){if(SAVE_LOCK||!CLOUD.user||!CLOUD.ready||CLOUD.paused||CLOUD.busy||document.hidden&&!force)return false;CLOUD.busy=true;try{const root=localStorage.getItem(CLOUD_OWNER);if(root!==CLOUD.user.id)throw new Error('Chưa chọn dữ liệu thuộc tài khoản này');const bundle=cloudCapture(),fingerprint=cloudFingerprint(bundle),binding=cloudLocal(CLOUD_BINDING);
if(!CLOUD.lease||Date.now()-CLOUD.lastLeaseAt>90000){const claimed=await cloudClaim();if(claimed.revision!==CLOUD.revision){const e=new Error('Máy chủ có bản mới; mở Tài khoản để chọn tiến trình');e.code='save_conflict';throw e;}}
if(!force&&binding?.fingerprint===fingerprint){const hb=await cloudApi('heartbeat',{clientId:cloudClientId});CLOUD.lastLeaseAt=Date.now();CLOUD.marketPending=hb.marketPending;if(hb.revision!==CLOUD.revision){const e=new Error('Tiến trình trên máy chủ đã thay đổi');e.code='save_conflict';throw e;}cloudStatus('Đã lưu · '+new Date(CLOUD.lastSaved||Date.now()).toLocaleTimeString('vi-VN'));return true;}
cloudStatus('Đang đồng bộ…');const r=await cloudApi('save',{clientId:cloudClientId,revision:CLOUD.revision,bundle});CLOUD.revision=r.revision;CLOUD.marketPending=r.marketPending;CLOUD.lastSaved=r.updatedAt;CLOUD.lastLeaseAt=Date.now();cloudSaveBinding(fingerprint);cloudStatus('Đã lưu · '+new Date(r.updatedAt).toLocaleTimeString('vi-VN'));await cloudLinkPvp();return true;
}catch(e){cloudFail(e);return false;}finally{CLOUD.busy=false;}}
async function cloudBootstrap(){const generation=cloudAuthGeneration;try{const r=await cloudApi('me');if(generation!==cloudAuthGeneration)return;CLOUD.user=r.user;CLOUD.meta=r;const binding=cloudLocal(CLOUD_BINDING),root=localStorage.getItem(CLOUD_OWNER);CLOUD.ready=!CLOUD.detachedBundle&&root===r.user.id&&binding?.id===r.user.id;CLOUD.revision=binding?.id===r.user.id?binding.revision:0;CLOUD.lastSaved=binding?.lastSaved||0;
if(CLOUD.ready){if(r.revision!==CLOUD.revision){CLOUD.paused=true;cloudStatus('Có bản mới trên máy chủ · hãy chọn tiến trình');}else{CLOUD.paused=false;await cloudSync();}}else cloudStatus('Đã đăng nhập · chọn dữ liệu để chơi');
}catch(e){if(generation!==cloudAuthGeneration)return;if(e.code==='cloud_login'){CLOUD.user=null;CLOUD.ready=false;cloudStatus('Chưa đăng nhập');}else cloudFail(e);}cloudInjectButtons();}
function cloudInstall(bundle,slot,previous=false){if(!bundle||bundle.v!==1||bundle.slots?.length!==3)throw new Error('Bản lưu cloud không hợp lệ');cloudArchive();const old=cloudRootKeys().concat([CLOUD_OWNER,CLOUD_BINDING,'jxidle_cloud_tab']).reduce((out,k)=>(out[k]=localStorage.getItem(k),out),{});cloudPut('jxidle_cloud_install_journal',{raw:old});const settings=bundle.slots.map((_,i)=>{try{return unpack(localStorage.getItem(slotKey(i))||'{}').state?.snd}catch(e){return null}});SAVE_LOCK=true;
try{for(const key of cloudRootKeys())localStorage.removeItem(key);for(let i=0;i<3;i++){const state=bundle.slots[i];if(!state)continue;const clean=cloudClean(state);if(settings[i])clean.snd=settings[i];localStorage.setItem(slotKey(i),pack(clean));sealWrite(i,clean.mode);localStorage.setItem(slotKey(i)+'_kps',String(clean.kps||.2));}for(const [key,state]of Object.entries(bundle.shared||{}))if(CLOUD_SHARED.includes(key))localStorage.setItem(key,pack(state));localStorage.setItem(SLOT_PTR,Number.isInteger(slot)&&bundle.slots[slot]?String(slot):'menu');CLOUD.ready=true;CLOUD.paused=false;cloudSaveBinding(previous?'':cloudFingerprint(bundle));localStorage.removeItem('jxidle_cloud_install_journal');
}catch(e){cloudRecoverStorage();CLOUD.ready=false;CLOUD.paused=true;SAVE_LOCK=false;throw new Error('Không đủ bộ nhớ để tải tiến trình; dữ liệu cũ được giữ');}
location.reload();}
function cloudRows(bundle){return (bundle?.slots||[null,null,null]).map((s,i)=>`<div class="cloudSlot"><span><b>Ô ${i+1} · ${s?esc(s.name||FAC[s.fac]?.n||'Nhân vật'):'Trống'}</b><small>${s?esc(MODES[s.mode]?.n||s.mode)+' · Cấp '+s.lvl:'Chưa có nhân vật'}</small></span>${s?`<button class="btn sm" data-cloud-play="${i}">Chơi tiếp</button>`:''}</div>`).join('');}
function cloudClose(){if(cloudEntryPending)return;document.getElementById('cloudPanel').classList.add('hidden');document.getElementById('app').inert=!!CLOUD.detachedBundle;}
function cloudShow(html){const panel=document.getElementById('cloudPanel');panel.classList.remove('hidden');document.getElementById('app').inert=true;document.getElementById('cloudBody').innerHTML=html;panel.querySelectorAll('[data-cloud-close]').forEach(b=>b.onclick=cloudClose);}
function cloudError(e){cloudFail(e);const error=document.getElementById('cloudError');if(error)error.textContent=e.message;else toast(e.message);}
function cloudGuestPlay(){cloudAuthGeneration++;CLOUD.user=null;CLOUD.ready=false;cloudEntryPending=false;try{sessionStorage.setItem('jxidle_cloud_guest_entry','1')}catch(e){}lastT=performance.now();cloudClose();cloudInjectButtons();}
function cloudEntryComplete(){cloudEntryPending=false;try{sessionStorage.removeItem('jxidle_cloud_guest_entry')}catch(e){}lastT=performance.now();cloudClose();}
async function cloudEnterAccount(){const remote=await cloudApi('load');CLOUD.meta=remote;const local=cloudCapture(false);if(!remote.hasSave&&!local.slots.some(Boolean)){const claimed=await cloudClaim();if(claimed.revision!==remote.revision)throw new Error('Tiến trình vừa thay đổi; mở lại tài khoản để tiếp tục');CLOUD.revision=remote.revision;CLOUD.lastSaved=remote.updatedAt||0;cloudInstall({v:1,slots:[null,null,null],shared:{}},null);return;}await cloudAccountMenu();}
async function cloudStartup(){if(cloudEntryPending)cloudAuthForm();await cloudBootstrap();if(!cloudEntryPending)return;if(!CLOUD.user){if(!document.getElementById('cloudAuthForm'))cloudAuthForm();return;}if(CLOUD.ready&&!CLOUD.paused){cloudEntryComplete();return;}try{await cloudEnterAccount()}catch(e){cloudAuthForm();cloudError(e);}}
async function cloudAuthForm(action='login'){
  const registering=action==='register';
  cloudShow(`<h3>${registering?'Tạo tài khoản':'Đăng nhập'}</h3><p class="desc">Lưu nhân vật và kho để chơi tiếp trên máy khác.</p><form id="cloudAuthForm"><label>Tên đăng nhập<input id="cloudUsername" name="username" autocomplete="username" minlength="4" maxlength="24" required pattern="[A-Za-z0-9_]{4,24}" placeholder="Tối thiểu 4 ký tự: chữ không dấu, số hoặc _"></label><label>Mật khẩu<input id="cloudPassword" name="password" placeholder="Tối thiểu 4 ký tự" type="password" autocomplete="${registering?'new-password':'current-password'}" minlength="4" maxlength="128" required></label>${registering?'<p class="desc">Bạn phải tự ghi nhớ tên đăng nhập và mật khẩu. Trò chơi không có chức năng khôi phục hoặc đặt lại mật khẩu.</p><label><input type="checkbox" id="cloudRememberCredentials" required> Tôi hiểu và sẽ tự ghi nhớ tên đăng nhập, mật khẩu</label>':''}<p id="cloudError" class="bad" role="alert"></p><div class="btnrow"><button class="btn" id="cloudAuthSubmit" type="submit">${registering?'Tạo tài khoản':'Đăng nhập'}</button>${cloudEntryPending?'':'<button class="btn" type="button" data-cloud-close>Đóng</button>'}</div></form><div class="btnrow"><button class="btn" id="cloudAuthSwitch">${registering?'Đăng nhập':'Đăng ký'}</button><button class="btn" id="cloudGuestPlay" type="button">Chơi ngay · không cần tài khoản</button></div><small>Đã đăng nhập: tự lưu lên tài khoản mỗi 30 giây. Chơi không tài khoản: lưu trên máy này.</small>`);
  document.getElementById('cloudGuestPlay').onclick=cloudGuestPlay;
  document.getElementById('cloudAuthSwitch').onclick=()=>cloudAuthForm(registering?'login':'register');
  document.getElementById('cloudAuthForm').onsubmit=async e=>{e.preventDefault();const generation=++cloudAuthGeneration;const btn=document.getElementById('cloudAuthSubmit');const label=btn.textContent;btn.disabled=true;btn.textContent=registering?'Đang tạo tài khoản…':'Đang đăng nhập…';document.activeElement?.blur();try{let turnstile='';if(registering){const cfg=await fetch('/api/config').then(r=>r.json());if(cfg.turnstile)turnstile=await onlTurnstile(cfg.turnstile);}const r=await cloudApi(action,{username:document.getElementById('cloudUsername').value,password:document.getElementById('cloudPassword').value,turnstile});if(generation!==cloudAuthGeneration)return;CLOUD.user=r.user;CLOUD.ready=false;CLOUD.paused=false;CLOUD.lease=false;cloudEntryPending=true;cloudInjectButtons();try{sessionStorage.removeItem('jxidle_cloud_guest_entry')}catch(e){}cloudStatus('Đã đăng nhập · chọn nhân vật để chơi tiếp');await cloudEnterAccount();}catch(error){if(generation===cloudAuthGeneration)cloudError(error);}finally{btn.disabled=false;btn.textContent=label;}};
}
async function cloudLoadChoice(slot,previous=false){try{const claimed=await cloudClaim(true);const remote=await cloudApi('load'+(previous?'?previous=1':''));if(!remote.bundle)throw new Error('Chưa có bản lưu để tải');if(remote.revision!==claimed.revision)throw new Error('Bản lưu vừa thay đổi, hãy mở lại danh sách');CLOUD.revision=remote.revision;CLOUD.lastSaved=remote.updatedAt;if(previous){if(!confirm('Khôi phục bản lưu trước? Bản hiện tại ở máy được giữ riêng.'))return;}
cloudInstall(remote.bundle,slot,previous);}catch(e){cloudError(e);}}
async function cloudUseLocal(archive=false){try{const current=archive==='tab'?JSON.parse(sessionStorage.getItem('jxidle_cloud_unsaved')||'null')?.bundle:archive?cloudLocal('jxidle_cloud_archive_'+CLOUD.user.id)?.bundle:cloudCapture();if(!current)throw new Error('Chưa có bản lưu tại máy');const preview=await cloudApi('load');const text=preview.hasSave?'Thay bản trên tài khoản bằng dữ liệu này? Bản cloud cũ được giữ làm bản lưu trước.':'Đưa cả ba ô nhân vật và các kho tại máy lên tài khoản?';if(!confirm(text))return;const claimed=await cloudClaim(true);if(claimed.revision!==preview.revision)throw new Error('Có tiến trình mới vừa được lưu, hãy kiểm tra lại trước khi thay thế');
cloudArchive();CLOUD.revision=claimed.revision;const r=await cloudApi('save',{clientId:cloudClientId,revision:CLOUD.revision,bundle:current});CLOUD.revision=r.revision;CLOUD.lastSaved=r.updatedAt;CLOUD.ready=true;CLOUD.paused=false;await cloudLinkPvp();cloudInstall(current,archive?null:SLOT);}catch(e){cloudError(e);}}
async function cloudLogout(){cloudAuthGeneration++;try{if(CLOUD.ready&&!CLOUD.paused&&!await cloudSync(true)){if(!confirm('Chưa lưu được lên cloud. Giữ bản tại máy rồi đăng xuất?'))return;}cloudArchive();await cloudApi('logout',{});const archived=cloudLocal('jxidle_cloud_archive_guest');SAVE_LOCK=true;for(const key of cloudRootKeys()){const value=archived?.raw?.[key];if(value!=null)localStorage.setItem(key,value);else localStorage.removeItem(key);}localStorage.removeItem(CLOUD_OWNER);localStorage.removeItem(CLOUD_BINDING);location.reload();}catch(e){cloudError(e);}}
async function cloudAccountMenu(){if(!CLOUD.user){cloudAuthForm();return;}cloudShow(`<h3>Tài khoản · ${esc(CLOUD.user.username)}</h3><p id="cloudState">${esc(CLOUD.status)}</p><p id="cloudError" class="bad" role="alert"></p><p>Đang tải danh sách nhân vật…</p><button class="btn" data-cloud-close>Đóng</button>`);try{const r=await cloudApi('load');CLOUD.meta=r;CLOUD.preview=r.bundle;const ownArchive=cloudLocal('jxidle_cloud_archive_'+CLOUD.user.id);let tabArchive=null;try{tabArchive=JSON.parse(sessionStorage.getItem('jxidle_cloud_unsaved')||'null')}catch(e){}cloudShow(`<h3>Tài khoản · ${esc(CLOUD.user.username)}</h3><p id="cloudState">${esc(CLOUD.status)}</p><p class="desc">${r.updatedAt?'Bản tài khoản: '+new Date(r.updatedAt).toLocaleString('vi-VN'):'Tài khoản chưa có tiến trình.'}</p>${CLOUD.paused?'<p class="bad">Đồng bộ đang dừng. Chọn bản tài khoản để chơi tiếp, hoặc chọn rõ bản tại máy để thay thế.</p>':''}<div class="cloudSlots">${cloudRows(r.bundle)}</div><p class="desc">Chơi tiếp sẽ chuyển quyền chơi sang máy này và tải cả ba ô cùng kho. Bản đang có tại máy được giữ riêng.</p><p id="cloudError" class="bad" role="alert"></p><div class="btnrow"><button class="btn" id="cloudSaveNow" ${CLOUD.ready&&!CLOUD.paused?'':'disabled'}>Lưu ngay</button><button class="btn" id="cloudUseLocal">${r.hasSave?'Dùng bản tại máy':'Đưa dữ liệu máy này lên'}</button>${tabArchive&&(tabArchive.owner===CLOUD.user.id||tabArchive.owner==='guest')?'<button class="btn" id="cloudUseTab">Bản chưa đồng bộ của tab này</button>':''}${ownArchive?'<button class="btn" id="cloudUseArchive">Bản lưu riêng của tài khoản ở máy này</button>':''}${r.previousRevision?'<button class="btn" id="cloudPrevious">Khôi phục bản trước</button>':''}<button class="btn" id="cloudLogout">Đăng xuất</button><button class="btn" data-cloud-close>${cloudEntryPending?'Vào game':'Đóng'}</button></div><small>Tự lưu mỗi 30 giây khi đang chơi. Trước khi chuyển máy, bấm Lưu ngay và đợi báo thành công. Mất mạng vẫn lưu tại máy.</small>`);
if(cloudEntryPending)document.querySelectorAll('[data-cloud-close]').forEach(b=>{b.disabled=!CLOUD.ready||CLOUD.paused;b.onclick=cloudEntryComplete;});
document.querySelectorAll('[data-cloud-play]').forEach(b=>b.onclick=()=>cloudLoadChoice(+b.dataset.cloudPlay));document.getElementById('cloudSaveNow').onclick=async()=>{if(await cloudSync(true))toast('Đã lưu lên tài khoản');};document.getElementById('cloudUseLocal').onclick=()=>cloudPreviewLocal(false);if(document.getElementById('cloudUseTab'))document.getElementById('cloudUseTab').onclick=()=>cloudPreviewLocal('tab');if(document.getElementById('cloudUseArchive'))document.getElementById('cloudUseArchive').onclick=()=>cloudPreviewLocal(true);if(document.getElementById('cloudPrevious'))document.getElementById('cloudPrevious').onclick=()=>cloudLoadChoice(null,true);document.getElementById('cloudLogout').onclick=cloudLogout;
}catch(e){cloudError(e);}}
function cloudPreviewLocal(archive){try{const bundle=archive==='tab'?JSON.parse(sessionStorage.getItem('jxidle_cloud_unsaved')||'null')?.bundle:archive?cloudLocal('jxidle_cloud_archive_'+CLOUD.user.id)?.bundle:cloudCapture();if(!bundle)throw new Error('Không có bản lưu tại máy');cloudShow(`<h3>${archive?'Bản lưu riêng tại máy':'Dữ liệu tại máy'}</h3>${cloudRows(bundle).replace(/<button class="btn sm" data-cloud-play="\d">Chơi tiếp<\/button>/g,'')}<p>Bao gồm kho chung, vật liệu và bộ sưu tập của các chế độ. Bản này sẽ thay dữ liệu trên tài khoản.</p><p id="cloudError" class="bad" role="alert"></p><div class="btnrow"><button class="btn" id="cloudUploadChoice">Lưu bản này lên tài khoản</button><button class="btn" id="cloudBack">Quay lại</button></div>`);document.getElementById('cloudUploadChoice').onclick=()=>cloudUseLocal(archive);document.getElementById('cloudBack').onclick=cloudAccountMenu;}catch(e){cloudError(e);}}
function cloudInjectButtons(){if(window.accountAdminRefresh)window.accountAdminRefresh();const ov=document.getElementById('jxOverflow');if(ov&&!document.getElementById('jxCloud')){const b=document.createElement('button');b.className='rbtn';b.id='jxCloud';b.dataset.ic='char';b.title='Tài khoản và lưu cloud';b.innerHTML='<i></i><span class="sk">Tài khoản</span>';b.onclick=cloudAccountMenu;const world=document.getElementById('jxWorld');if(world)ov.appendChild(world);ov.appendChild(b);}const body=document.getElementById('mBody');if(body&&(body.querySelector('#pfName')||body.querySelector('h3')?.textContent==='Chọn nhân vật')&&!document.getElementById('cloudStartButton')){const b=document.createElement('button');b.id='cloudStartButton';b.className='btn';b.textContent=CLOUD.user?'Tài khoản · '+CLOUD.user.username:'Đăng nhập / Đăng ký tài khoản';b.onclick=cloudAccountMenu;body.insertBefore(b,body.children[1]||null);}}
(function(){const panel=document.createElement('section');panel.id='cloudPanel';panel.className='hidden';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Tài khoản và tiến trình');panel.innerHTML='<div id="cloudBody"></div>';document.body.appendChild(panel);panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape')cloudClose();});const body=document.getElementById('mBody');if(body)new MutationObserver(cloudInjectButtons).observe(body,{childList:true});cloudInjectButtons();const originalFrame=frame;frame=function(time){if(CLOUD.detachedBundle||cloudEntryPending||window.JXADMINBUSY){lastT=time;requestAnimationFrame(frame);return;}originalFrame(time);};const render=renderMore;renderMore=function(){render.apply(this,arguments);const t=document.getElementById('t-more');if(t){const card=document.createElement('div');card.className='card';card.innerHTML='<h3>Tài khoản và lưu cloud</h3><p>'+esc(CLOUD.status)+'</p><button class="btn" id="cloudSystemButton">Mở tài khoản</button>';t.prepend(card);document.getElementById('cloudSystemButton').onclick=cloudAccountMenu;}};cloudStartup();setInterval(()=>{if(document.hidden||cloudEntryPending)return;if(CLOUD.user&&CLOUD.ready)cloudSync();},CLOUD_SYNC_MS);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(S&&S.fac&&!SAVE_LOCK)save();cloudSync(true);}else if(CLOUD.user&&CLOUD.ready)cloudSync();});addEventListener('storage',e=>{const changedOwner=e.key===CLOUD_OWNER&&(e.newValue||'guest')!==cloudLoadedOwner;const changedTab=e.key==='jxidle_cloud_tab'&&CLOUD.ready&&e.newValue!==cloudClientId;if(changedOwner||changedTab){CLOUD.paused=true;CLOUD.lease=false;if(changedOwner)CLOUD.ready=false;cloudStatus('Quyền chơi đã chuyển sang tab khác; dữ liệu tab này được giữ riêng');try{const backup=cloudLocal('jxidle_cloud_archive_'+cloudLoadedOwner)?.bundle||cloudCapture(false);CLOUD.detachedBundle=backup;if(S&&S.fac){const state=cloudClean(S);delete state.snd;backup.slots[SLOT]=state;}sessionStorage.setItem('jxidle_cloud_unsaved',JSON.stringify({owner:cloudLoadedOwner,bundle:backup}));}catch(error){}SAVE_LOCK=true;document.getElementById('app').inert=true;cloudBootstrap().then(cloudAccountMenu);}});})();
