'use strict';
const MASK_ITEMS=new Map((window.JMASK?.items||[]).map(m=>[m.id,m]));
let maskPage=0,maskQuery='';
function ownedMasks(state=S){return Array.isArray(state?.maskOwned)?state.maskOwned:[];}
function equippedMask(state=S){return ownedMasks(state).includes(state?.maskId)?MASK_ITEMS.get(state.maskId)||null:null;}
function buyMask(id){const item=MASK_ITEMS.get(id);if(!S?.fac||!item)return false;if(ownedMasks().includes(id)){toast('Đã sở hữu mặt nạ này');return false;}if(!Number.isSafeInteger(S.knb)||S.knb<item.price){toast('Không đủ Kim Nguyên Bảo');return false;}S.knb-=item.price;S.maskOwned=[...ownedMasks(),id];save();updateTop();maskShopModal();toast('Đã mua '+item.n);return true;}
function wearMask(id){if(id!==null&&(!MASK_ITEMS.has(id)||!ownedMasks().includes(id)))return false;const old=equippedMask();S.maskId=id;const next=equippedMask();if(old&&old.id!==next?.id)for(const sheet of Object.values(old.anim)){const image=IMG[sheet.f];if(image){image.src="";delete IMG[sheet.f];}}if(next)for(const act of ["st","run","at"])img(next.anim[act].f);save();renderChar();if(document.getElementById('maskShopList'))maskShopModal();toast(id===null?'Đã tháo mặt nạ':'Đã đeo '+MASK_ITEMS.get(id).n);return true;}
function maskShopModal(){if(!S?.fac)return;const all=[...MASK_ITEMS.values()].filter(m=>!maskQuery||noMark(m.n).includes(noMark(maskQuery))),pages=Math.max(1,Math.ceil(all.length/16));maskPage=Math.min(maskPage,pages-1);const current=equippedMask();
modal(`<h3>Mặt nạ · Shop Kim Nguyên Bảo</h3><p class="desc">Chỉ đổi ngoại hình và hoạt ảnh. Không cộng chỉ số, không đổi lực chiến. Sở hữu vĩnh viễn.</p><div class="row"><b>${fmt(S.knb||0)} KNB</b><span class="sp"></span><button class="btn sm" id="maskBack">Bảo vật</button></div><p>Đang đeo: <b>${esc(current?.n||'Không có')}</b>${current?' <button class="btn sm" id="maskRemove">Tháo mặt nạ</button>':''}</p><div class="row"><input id="maskSearch" type="search" value="${esc(maskQuery)}" placeholder="Tìm mặt nạ…"><button class="btn sm" id="maskFind">Tìm</button></div><div id="maskShopList" class="mask-shop-list">${all.slice(maskPage*16,maskPage*16+16).map(m=>{const owned=ownedMasks().includes(m.id),wear=current?.id===m.id;return`<article><img loading="lazy" src="${esc(m.icon)}" alt=""><div><b>${esc(m.n)}</b><small>${owned?'Đã sở hữu':m.price+' Kim Nguyên Bảo'}</small><button class="btn sm" data-mask="${m.id}" data-owned="${owned}" ${wear||!owned&&(S.knb||0)<m.price?'disabled':''}>${wear?'Đang đeo':owned?'Đeo':'Mua'}</button></div></article>`;}).join('')||'<p>Không tìm thấy mặt nạ.</p>'}</div><div class="row"><button class="btn sm" id="maskPrev" ${maskPage?'':'disabled'}>‹ Trước</button><span class="sp"></span>${maskPage+1}/${pages}<span class="sp"></span><button class="btn sm" id="maskNext" ${maskPage+1<pages?'':'disabled'}>Sau ›</button></div>`,()=>{document.getElementById('maskBack').onclick=treasureShopModal;const remove=document.getElementById('maskRemove');if(remove)remove.onclick=()=>wearMask(null);document.getElementById('maskFind').onclick=()=>{maskQuery=document.getElementById('maskSearch').value.slice(0,80);maskPage=0;maskShopModal();};document.getElementById('maskSearch').onkeydown=e=>{if(e.key==='Enter')document.getElementById('maskFind').click();};document.getElementById('maskPrev').onclick=()=>{maskPage--;maskShopModal();};document.getElementById('maskNext').onclick=()=>{maskPage++;maskShopModal();};document.querySelectorAll('[data-mask]').forEach(b=>b.onclick=()=>b.dataset.owned==='true'?wearMask(+b.dataset.mask):buyMask(+b.dataset.mask));});}
function maskActDuration(sheet,act){const seconds=(sheet.per||sheet.n)*(sheet.interval||75)/1000;return ["at","at2","mag","hurt"].includes(act)?Math.min(.65,seconds):seconds;}
function drawMaskedCharacter(c,x,y,act,dir,t,scale,alpha,state){const mask=equippedMask(state);if(!mask)return null;const sheet=mask.anim[act]||mask.anim.st,im=img(sheet.f);if(!im.complete||!im.naturalWidth)return null;const once=['at','at2','mag','hurt','die'].includes(act),duration=maskActDuration(sheet,act),phase=once?Math.min(Math.max(0,t||0)/duration,.999999):(Math.max(0,t||0)/duration)%1,column=Math.min(sheet.n-1,Math.floor(phase*sheet.n)),row=dollRow(dir,sheet.d),eff=dollEffScale(scale);c.save();c.globalAlpha=alpha==null?1:alpha;if(typeof drawBodyShadow==='function')drawBodyShadow(c,im,sheet,column,row,x,y,eff*.6,c.globalAlpha);c.drawImage(im,column*sheet.w,row*sheet.h,sheet.w,sheet.h,x-sheet.ax*eff,y-sheet.ay*eff,sheet.w*eff,sheet.h*eff);c.restore();return sheet.h*eff;}
const drawUnmaskedDoll=drawDoll;
drawDoll=function(c,x,y,act,dir,t,scale,alpha,state){const character=state||(typeof S!=='undefined'?S:null);const height=drawMaskedCharacter(c,x,y,act,dir,t,scale,alpha,character);return height===null?drawUnmaskedDoll(c,x,y,act,dir,t,scale,alpha,state):height;};

const unmaskedActLen=dollActLen;
dollActLen=function(state,act){const mask=equippedMask(state),sheet=mask&&(mask.anim[act]||mask.anim.st);return sheet?maskActDuration(sheet,act):unmaskedActLen(state,act);};
