import {ensureEconomy,economyCommit,economyBackup} from './economy.js';
import {checkStateSecurity} from './state-security.js';
// Tài khoản lưu cloud độc lập với đăng ký PvP. Cookie chỉ gửi cùng origin.
import { HttpError, randomToken, sha256Hex, ipHash } from './http.js';
import {marketRoute,marketSaveCheck} from './black-market.js';
import { rateLimit } from './db.js';
import { GAME } from '../gen/game.js';
import { isAccountAdmin, requireAccountAdmin, adminCatalogue, createAdminGrant } from './account-admin.js';

export const CLOUD_MAX_BYTES=900*1024, PASSWORD_ITERATIONS=100000, LEASE_MS=180000;
const SESSION_MS=30*86400000, enc=new TextEncoder();
export const SHARED_KEYS=['stash','clan','guild','collections'].flatMap(name=>['','_ctc','_phlt'].map(suffix=>'jxidle_'+name+suffix));
function enabled(env){if(String(env.CLOUD_ACCOUNTS_ENABLED)==='0')throw new HttpError(503,'cloud_disabled','Đồng bộ tài khoản đang tạm tắt; dữ liệu tại máy vẫn được giữ');}
function originCheck(req){if(req.method==='POST'&&req.headers.get('origin')!==new URL(req.url).origin)throw new HttpError(403,'bad_origin','Yêu cầu phải gửi từ trang trò chơi');}
function response(data,cookie){const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-game-time':String(Date.now())};if(cookie)headers['set-cookie']=cookie;return new Response(JSON.stringify(data),{headers});}
function cookie(token,maxAge=SESSION_MS/1000){return `vltk_cloud=${token}; Path=/api; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;}
function tokenOf(req){return /(?:^|;\s*)vltk_cloud=([A-Za-z0-9_-]{20,80})(?:;|$)/.exec(req.headers.get('cookie')||'')?.[1]||'';}
export function username(value){const name=String(value||'').trim().toLowerCase();if(!/^[a-z0-9_]{4,24}$/.test(name))throw new HttpError(400,'bad_username','Tên đăng nhập 4–24 ký tự: chữ không dấu, số hoặc _');return name;}
const publicUser=acc=>({id:acc.id,username:acc.username,isAdmin:isAccountAdmin(acc)});
function password(value){if(typeof value!=='string'||value.length<4||value.length>128)throw new HttpError(400,'bad_password','Mật khẩu phải dài 4–128 ký tự');return value;}
export async function passwordHash(value,salt,iterations=PASSWORD_ITERATIONS){const key=await crypto.subtle.importKey('raw',enc.encode(value),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations},key,256);return [...new Uint8Array(bits)].map(n=>n.toString(16).padStart(2,'0')).join('');}
function equal(a,b){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
export async function cloudAuth(req,env){const token=tokenOf(req);if(!token)throw new HttpError(401,'cloud_login','Bạn cần đăng nhập tài khoản');const row=await env.DB.prepare('SELECT a.id,a.username,s.token_hash FROM cloud_sessions s JOIN cloud_accounts a ON a.id=s.account_id WHERE s.token_hash=?1 AND s.expires_at>?2').bind(await sha256Hex(token),Date.now()).first();if(!row)throw new HttpError(401,'cloud_login','Phiên đăng nhập đã hết hạn');return row;}
async function limited(req,env,key,max=20){const ih=await ipHash(req,env);if(!await rateLimit(env.DB,'cloud:'+key+':'+ih,max,3600))throw new HttpError(429,'cloud_rate','Thao tác quá nhiều, vui lòng thử lại sau');}
async function session(env,id){const token=randomToken(32),now=Date.now();await env.DB.prepare('INSERT INTO cloud_sessions(token_hash,account_id,created_at,expires_at) VALUES(?1,?2,?3,?4)').bind(await sha256Hex(token),id,now,now+SESSION_MS).run();await env.DB.prepare('DELETE FROM cloud_sessions WHERE expires_at<=?1').bind(now).run();return token;}
async function captcha(req,env,value){if(!env.TURNSTILE_SECRET)return;if(!value)throw new HttpError(403,'captcha','Cần xác minh chống bot');const form=new FormData();form.append('secret',env.TURNSTILE_SECRET);form.append('response',String(value));const ip=req.headers.get('cf-connecting-ip');if(ip)form.append('remoteip',ip);const r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:form});if(!(await r.json()).success)throw new HttpError(403,'captcha','Xác minh chống bot không thành công');}
async function register(req,env,body){await limited(req,env,'register',5);await captcha(req,env,body.turnstile);const name=username(body.username),pass=password(body.password);if(name==='danh')throw new HttpError(409,'username_reserved','Tên danh được dành riêng cho tài khoản admin');const id=randomToken(18),salt=randomToken(18),hash=await passwordHash(pass,salt);try{await env.DB.batch([env.DB.prepare('INSERT INTO cloud_accounts(id,username,password_hash,password_salt,password_iterations,created_at) VALUES(?1,?2,?3,?4,?5,?6)').bind(id,name,hash,salt,PASSWORD_ITERATIONS,Date.now()),env.DB.prepare('INSERT INTO cloud_saves(account_id,revision) VALUES(?1,0)').bind(id)]);}catch(e){if(/UNIQUE/i.test(e.message))throw new HttpError(409,'username_taken','Tên đăng nhập đã được sử dụng');throw e;}
return response({user:publicUser({id,username:name})},cookie(await session(env,id)));}
async function login(req,env,body){await limited(req,env,'login');const name=username(body.username),pass=password(body.password);const row=await env.DB.prepare('SELECT * FROM cloud_accounts WHERE username=?1').bind(name).first();const hash=await passwordHash(pass,row?.password_salt||'unknown-account-salt',row?.password_iterations||PASSWORD_ITERATIONS);if(!row||!equal(hash,row.password_hash))throw new HttpError(401,'bad_credentials','Tên đăng nhập hoặc mật khẩu không đúng');return response({user:publicUser(row)},cookie(await session(env,row.id)));}
function clean(value,depth=0){if(depth>40)throw new HttpError(400,'bad_save','Dữ liệu lưu không hợp lệ');if(value===null||typeof value==='string'||typeof value==='boolean')return value;if(typeof value==='number'){if(!Number.isFinite(value))throw new HttpError(400,'bad_save');return value;}if(Array.isArray(value))return value.map(v=>clean(v,depth+1));if(value&&typeof value==='object'){const out={};for(const [key,v]of Object.entries(value)){if(['__proto__','constructor','prototype','token','password','secret','authorization','sandbox','admin'].includes(key.toLowerCase()))continue;out[key]=clean(v,depth+1);}return out;}throw new HttpError(400,'bad_save');}
export function cleanBundle(value){if(!value||value.v!==1||!Array.isArray(value.slots)||value.slots.length!==3)throw new HttpError(400,'bad_save','Cần dữ liệu của đúng ba ô nhân vật');const slots=value.slots.map(state=>{if(state===null)return null;if(!state||typeof state!=='object'||Array.isArray(state)||!Object.hasOwn(GAME.FAC,state.fac)||!Object.hasOwn(GAME.MODES,state.mode)||!Number.isInteger(state.lvl)||state.lvl<1||state.lvl>300)throw new HttpError(400,'bad_save','Nhân vật hoặc chế độ không hợp lệ');const out=checkStateSecurity(clean(state));delete out.snd;return out;});const shared={};for(const key of SHARED_KEYS){const v=value.shared?.[key];if(v!=null){if(typeof v!=='object'||Array.isArray(v))throw new HttpError(400,'bad_save','Dữ liệu kho không hợp lệ');shared[key]=clean(v);checkStateSecurity(shared[key]);}}const bundle={v:1,slots,shared};if(enc.encode(JSON.stringify(bundle)).length>CLOUD_MAX_BYTES)throw new HttpError(413,'save_too_large','Dữ liệu vượt giới hạn 900 KB, chưa thể đồng bộ');return bundle;}
function client(body){if(!/^[A-Za-z0-9_-]{16,80}$/.test(body.clientId||''))throw new HttpError(400,'bad_client');return body.clientId;}
async function saveRow(env,id){return env.DB.prepare('SELECT * FROM cloud_saves WHERE account_id=?1').bind(id).first();}
function metadata(row){return {revision:row.revision,updatedAt:row.updated_at||0,hasSave:!!row.snapshot,writer:row.write_label||'',writeUntil:row.write_until||0,previousRevision:row.previous_revision||0};}
export async function cloudRoute(req,env,body,url){originCheck(req);const path=url.pathname.slice('/api/cloud/'.length);if(path==='logout'&&req.method==='POST'){const token=tokenOf(req);if(token)await env.DB.prepare('DELETE FROM cloud_sessions WHERE token_hash=?1').bind(await sha256Hex(token)).run();return response({ok:true},cookie('',0));}enabled(env);
if(req.method==='POST'&&path==='register')return register(req,env,body);if(req.method==='POST'&&path==='login')return login(req,env,body);
const acc=await cloudAuth(req,env),econ=await ensureEconomy(env,acc);
if(path==='economy/backup'&&req.method==='GET')return response(await economyBackup(env,acc,url));
if(path==='economy/action'&&req.method==='POST'){if(!econ)throw new HttpError(409,'economy_disabled','Cơ chế kinh tế server chưa bật');return response(await economyCommit(env,acc,body,'action'));}
if(path==='save'&&req.method==='POST'&&econ){const result=await economyCommit(env,acc,body);result.marketPending=!!await env.DB.prepare("SELECT 1 FROM market_listings WHERE seller=?1 AND ((status='sold' AND claimed=0) OR (status='active' AND expires_at<=?2)) LIMIT 1").bind(acc.id,Date.now()).first();return response(result);}
if(path.startsWith('market/'))return response(await marketRoute(env,acc,body,url,req.method,cleanBundle));if(path.startsWith('admin/')){requireAccountAdmin(acc);if(req.method==='GET'&&path==='admin/catalogue')return response(adminCatalogue(url.searchParams));if(req.method==='POST'&&path==='admin/grant')return grantAdmin(req,env,acc,body);throw new HttpError(404,'not_found');}if(req.method==='GET'&&path==='me'){const row=await saveRow(env,acc.id);return response({user:publicUser(acc),economyVersion:econ?.v||0,...metadata(row)});}if(req.method==='GET'&&path==='load'){const row=await saveRow(env,acc.id),previous=url.searchParams.get('previous')==='1';return response({economyVersion:econ?.v||0,...metadata(row),bundle:JSON.parse((previous?row.previous_snapshot:row.snapshot)||'null'),loadedRevision:previous?row.previous_revision:row.revision});}
if(req.method==='POST'&&path==='link-pvp'){if(!Array.isArray(body.links)||body.links.length>3)throw new HttpError(400,'bad_links');const row=await saveRow(env,acc.id),bundle=JSON.parse(row.snapshot||'null');for(const link of body.links){if(!Number.isInteger(link.slot)||link.slot<0||link.slot>2||typeof link.token!=='string'||link.token.length>80)throw new HttpError(400,'bad_links');const pvp=await env.DB.prepare('SELECT a.id,a.token_hash,c.snapshot FROM accounts a LEFT JOIN chars c ON c.account_id=a.id WHERE a.token_hash=?1').bind(await sha256Hex(link.token)).first();const state=bundle?.slots[link.slot];if(!pvp||!GAME.isMode(state?.mode)||(econ?JSON.parse(pvp.snapshot||'null')?.cid!==state?.cid||JSON.parse(pvp.snapshot||'null')?.mode!==state?.mode:state?.online?.id!==pvp.id))throw new HttpError(403,'bad_pvp_link','Nhân vật PvP không khớp tài khoản');try{await env.DB.prepare('INSERT INTO cloud_pvp_links(cloud_account_id,slot,pvp_account_id) VALUES(?1,?2,?3) ON CONFLICT(cloud_account_id,slot) DO UPDATE SET pvp_account_id=excluded.pvp_account_id').bind(acc.id,link.slot,pvp.id).run();}catch(e){if(/UNIQUE/i.test(e.message))throw new HttpError(409,'pvp_linked','Nhân vật PvP đã liên kết tài khoản khác');throw e;}}return response({ok:true});}
if(req.method==='POST'&&path==='claim'){const owner=client(body),now=Date.now(),label=String(body.device||'Thiết bị').slice(0,60);const row=await env.DB.prepare('UPDATE cloud_saves SET write_owner=?2,write_label=?3,write_until=?4 WHERE account_id=?1 AND (write_owner=?2 OR write_until<=?5 OR write_owner IS NULL OR ?6=1) RETURNING revision,updated_at,snapshot,write_label,write_until,previous_revision').bind(acc.id,owner,label,now+LEASE_MS,now,body.takeover===true?1:0).first();if(!row)throw new HttpError(409,'device_busy','Một thiết bị khác đang chơi; chọn Chơi trên máy này để chuyển quyền');return response({ok:true,economyVersion:econ?.v||0,...metadata(row)});}
if(req.method==='POST'&&path==='release'){await env.DB.prepare('UPDATE cloud_saves SET write_owner=NULL,write_until=0 WHERE account_id=?1 AND write_owner=?2').bind(acc.id,client(body)).run();return response({ok:true});}
if(req.method==='POST'&&path==='heartbeat'){const now=Date.now();const row=await env.DB.prepare('UPDATE cloud_saves SET write_until=?3 WHERE account_id=?1 AND write_owner=?2 AND write_until>?4 RETURNING revision').bind(acc.id,client(body),now+LEASE_MS,now).first();if(!row)throw new HttpError(409,'device_changed','Quyền chơi đã chuyển sang máy khác; bản tại máy vẫn được giữ');return response({ok:true,revision:row.revision,marketPending:!!await env.DB.prepare("SELECT 1 FROM market_listings WHERE seller=?1 AND ((status='sold' AND claimed=0) OR (status='active' AND expires_at<=?2)) LIMIT 1").bind(acc.id,now).first()});}
if(req.method==='POST'&&path==='save'){if(!await rateLimit(env.DB,'cloud:save:'+acc.id,180,3600))throw new HttpError(429,'cloud_rate','Đồng bộ quá nhiều, thử lại sau');const bundle=cleanBundle(body.bundle),owner=client(body),revision=body.revision;if(!Number.isSafeInteger(revision)||revision<0)throw new HttpError(400,'bad_revision');await marketSaveCheck(env.DB,acc.id,bundle);const now=Date.now();const row=await env.DB.prepare(`UPDATE cloud_saves SET previous_snapshot=snapshot,previous_revision=revision,previous_updated_at=updated_at,snapshot=?4,revision=revision+1,updated_at=?5,write_until=?6 WHERE account_id=?1 AND revision=?2 AND write_owner=?3 AND write_until>?5 RETURNING revision,updated_at`).bind(acc.id,revision,owner,JSON.stringify(bundle),now,now+LEASE_MS).first();if(!row){const current=await saveRow(env,acc.id);if(current.write_owner!==owner||current.write_until<=now)throw new HttpError(409,'device_changed','Máy này không còn quyền đồng bộ');throw new HttpError(409,'save_conflict','Máy chủ đã có bản mới hơn; bản tại máy được giữ, hãy chọn dữ liệu để tiếp tục');}return response({ok:true,revision:row.revision,updatedAt:row.updated_at,marketPending:!!await env.DB.prepare("SELECT 1 FROM market_listings WHERE seller=?1 AND ((status='sold' AND claimed=0) OR (status='active' AND expires_at<=?2)) LIMIT 1").bind(acc.id,now).first()});}
throw new HttpError(404,'not_found');}

async function grantAdmin(req,env,acc,body){
 const owner=client(body),requestId=body.requestId;if(!/^[A-Za-z0-9_-]{20,80}$/.test(requestId||''))throw new HttpError(400,'bad_request_id');
 const previous=await env.DB.prepare('SELECT client_id,response_json FROM admin_grants WHERE account_id=?1 AND request_id=?2').bind(acc.id,requestId).first();if(previous){if(previous.client_id!==owner)throw new HttpError(409,'device_changed');return response(JSON.parse(previous.response_json));}
 if(!await rateLimit(env.DB,'admin:grant:'+acc.id,240,3600))throw new HttpError(429,'cloud_rate','Lấy quá nhiều lần; thử lại sau');
 const row=await saveRow(env,acc.id);if(row.write_owner!==owner||row.write_until<=Date.now())throw new HttpError(409,'device_changed','Máy này chưa có quyền đồng bộ');if(!Number.isSafeInteger(body.revision)||body.revision!==row.revision)throw new HttpError(409,'save_conflict','Tiến trình vừa thay đổi; đồng bộ lại trước khi lấy đồ');
 const bundle=cleanBundle(JSON.parse(row.snapshot||'null')),grant=createAdminGrant(bundle,body),state=grant.state,cleaned=cleanBundle(grant.bundle),now=Date.now();
 const changes={};if(grant.items.length){changes.items=grant.items;changes.uid=state.uid;changes.ml=state.ml;if(state.setSeen)changes.setSeen=state.setSeen;}else if(body.id.startsWith('m:')){const[,group,...key]=body.id.split(':');changes.material={group,key:key.join(':'),count:state.mats[group][key.join(':')]};}else if(body.id.startsWith('p:')){const p=GAME.J.potions[+body.id.split(':')[1]];changes.potion={kind:p.kind,tier:p.tier,count:state.potStock[p.kind][p.tier]};}else{const key=body.id==='tienThao'?'tienThaoUntil':body.id==='knb'?'knb':'gold';changes[key]=state[key];}
 const result={ok:true,revision:row.revision+1,updatedAt:now,slot:body.slot,cid:state.cid,changes,name:grant.name,quantity:grant.quantity},json=JSON.stringify(result);
 const updates=await env.DB.batch([
  env.DB.prepare('UPDATE cloud_saves SET previous_snapshot=snapshot,previous_revision=revision,previous_updated_at=updated_at,snapshot=?4,revision=revision+1,updated_at=?5,write_until=?6 WHERE account_id=?1 AND revision=?2 AND write_owner=?3 AND write_until>?5').bind(acc.id,row.revision,owner,JSON.stringify(cleaned),now,now+LEASE_MS),
  env.DB.prepare('INSERT INTO admin_grants(account_id,request_id,client_id,slot,entry_id,quantity,created_at,response_json) SELECT ?1,?2,?3,?4,?5,?6,?7,?8 WHERE changes()=1').bind(acc.id,requestId,owner,body.slot,body.id,grant.quantity,now,json)
 ]);
 if(!updates[0].meta.changes){const saved=await env.DB.prepare('SELECT client_id,response_json FROM admin_grants WHERE account_id=?1 AND request_id=?2').bind(acc.id,requestId).first();if(saved&&saved.client_id===owner)return response(JSON.parse(saved.response_json));throw new HttpError(409,'save_conflict','Tiến trình đã đổi; chưa cấp vật phẩm');}
 return response(result);
}
