import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {SCHEMA} from '../src/db.js';import {cloudRoute} from '../src/cloud-account.js';import {adminCatalogue,createAdminGrant} from '../src/account-admin.js';import {GAME as G} from '../gen/game.js';
function setup(){const sql=new DatabaseSync(':memory:');for(const q of SCHEMA)sql.exec(q);const DB={prepare(q){let args=[];return{bind(...v){args=v;return this},async first(){return sql.prepare(q).get(...args)||null},async run(){return{meta:{changes:sql.prepare(q).run(...args).changes}}},async all(){return{results:sql.prepare(q).all(...args)}}}},async batch(list){sql.exec('BEGIN');try{const r=[];for(const q of list)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};return{env:{DB},sql};}
async function route(env,path,body={},cookie='',method='POST',origin='https://game.example'){const req=new Request('https://game.example/api/cloud/'+path,{method,headers:{origin,cookie}}),response=await cloudRoute(req,env,body,new URL(req.url));return{data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]||cookie};}
async function register(env,name='normaluser'){return route(env,'register',{username:name,password:'password1234'});}
async function admin(env,sql){const user=await register(env,'adminseed');sql.prepare('UPDATE cloud_accounts SET username=? WHERE id=?').run('danh',user.data.user.id);return user;}
const clientId='device_abcdefghijklmnop';function bundle(mode='g2'){const s=G.newSave();Object.assign(s,{fac:'shaolin',mode,lvl:60,autoEquip:false});return{v:1,slots:[s,null,null],shared:{}};}
async function ready(env,cookie,b=bundle()){await route(env,'claim',{clientId},cookie);await route(env,'save',{clientId,revision:0,bundle:b},cookie);return b;}
const catalogue=group=>adminCatalogue(new URLSearchParams({group,mode:'g2'}));
test('admin role is derived from authenticated danh account; guests and ordinary users cannot list or grant',async()=>{const{env,sql}=setup(),normal=await register(env);assert.equal(normal.data.user.isAdmin,false);for(const path of ['admin/catalogue','admin/grant']){await assert.rejects(route(env,path,{username:'danh',isAdmin:true,admin:true},normal.cookie,path.endsWith('catalogue')?'GET':'POST'),e=>e.status===403);await assert.rejects(route(env,path,{},'',path.endsWith('catalogue')?'GET':'POST'),e=>e.status===401);}const a=await admin(env,sql);assert.equal((await route(env,'me',{},a.cookie,'GET')).data.user.isAdmin,true);const login=await route(env,'login',{username:'DANH',password:'password1234'});assert.equal(login.data.user.isAdmin,true);assert.ok((await route(env,'admin/catalogue?group=mount',{},a.cookie,'GET')).data.rows.length);sql.close();});
test('registration rejects reserved admin name and case-insensitive duplicate normal names',async()=>{const{env,sql}=setup();await assert.rejects(register(env,'DANH'),e=>e.code==='username_reserved');await register(env,'uniqueuser');await assert.rejects(register(env,'UNIQUEUSER'),e=>e.code==='username_taken');assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM cloud_accounts').get().n,1);sql.close();});
test('catalogue is paginated, includes every supported group, supports Vietnamese search and mode restrictions',()=>{for(const group of ['gear','mount','gold','platina','material','potion','other']){const c=catalogue(group);assert.ok(c.total>0,group);assert.ok(c.rows.length<=40);}assert.ok(catalogue('mount').total<310);const c=adminCatalogue(new URLSearchParams({group:'gear',q:'dao',d:'0'}));assert.ok(c.rows.length>0);assert.ok(c.rows.every(r=>r.d===0));assert.ok(adminCatalogue(new URLSearchParams({group:'material',q:'huyen tinh'})).rows.some(r=>r.n.includes('Huyền Tinh')));assert.equal(adminCatalogue(new URLSearchParams({group:'platina',mode:'ctc'})).rows[0].available,false);});
test('server grant persists locked gear with unique IDs and audit, replay never grants twice',async()=>{const{env,sql}=setup(),a=await admin(env,sql),b=bundle();b.slots[0].uid=1;b.slots[0].eq.armor={uid:500};await ready(env,a.cookie,b);const body={clientId,revision:1,requestId:crypto.randomUUID(),slot:0,id:catalogue('gear').rows[0].id,quantity:2,quality:1,enhance:10};const r=await route(env,'admin/grant',body,a.cookie);assert.equal(r.data.revision,2);assert.deepEqual(r.data.changes.items.map(it=>it.uid),[501,502]);assert.ok(r.data.changes.items.every(it=>it.locked&&it.enh===10));const again=await route(env,'admin/grant',body,a.cookie);assert.deepEqual(again.data,r.data);const saved=(await route(env,'load',{},a.cookie,'GET')).data;assert.equal(saved.bundle.slots[0].inv.length,2);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM admin_grants').get().n,1);await assert.rejects(route(env,'admin/grant',{...body,requestId:crypto.randomUUID()},a.cookie),e=>e.code==='save_conflict');sql.close();});
test('grants reject full inventory, invalid entries/quantity, unsupported mode and foreign device without changing saves',async()=>{const{env,sql}=setup(),a=await admin(env,sql),b=bundle('ctc');b.slots[0].inv=Array.from({length:60},(_,i)=>({uid:i+1}));await ready(env,a.cookie,b);const base={clientId,revision:1,requestId:crypto.randomUUID(),slot:0,id:catalogue('gear').rows[0].id,quantity:1};for(const [change,code] of [[{},'inventory_full'],[{id:'invalid'},'bad_item'],[{quantity:-1},'bad_grant'],[{id:catalogue('platina').rows[0].id},'mode_item'],[{clientId:'otherdevice_abcdefghijkl'},'device_changed']])await assert.rejects(route(env,'admin/grant',{...base,...change,requestId:crypto.randomUUID()},a.cookie),e=>e.code===code);assert.equal(sql.prepare('SELECT revision FROM cloud_saves').get().revision,1);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM admin_grants').get().n,0);sql.close();});
test('all equipment qualities, native set references and material/potion/currency/buff grants use game data',()=>{const old=G.newSave();G.setS(old);for(const quality of [0,1,2,3]){const b=bundle();const r=createAdminGrant(b,{slot:0,id:catalogue('gear').rows[0].id,quantity:1,quality});assert.equal(r.items[0].r,quality);assert.equal(G.getS(),old);}for(const group of ['mount','gold','platina']){const r=createAdminGrant(bundle(),{slot:0,id:catalogue(group).rows[0].id,quantity:1});assert.ok(r.items[0]);if(group!=='mount')assert.ok(r.items[0].refId);}const b=bundle();createAdminGrant(b,{slot:0,id:'m:ht:10',quantity:50});assert.equal(b.slots[0].mats.ht[10],50);createAdminGrant(b,{slot:0,id:'p:0',quantity:10});assert.equal(b.slots[0].potStock.life[1],10);createAdminGrant(b,{slot:0,id:'knb',quantity:100});assert.equal(b.slots[0].knb,100);createAdminGrant(b,{slot:0,id:'tienThao',quantity:2});assert.ok(b.slots[0].tienThaoUntil>Date.now()+7199000);assert.equal(G.getS(),old);});

test('mount catalogue merges equal names and stats across levels, preserves different stats and grants the lowest-level representative',()=>{const rows=[];for(let page=0;;page++){const c=adminCatalogue(new URLSearchParams({group:'mount',page:String(page)}));rows.push(...c.rows);if(page+1>=c.pages)break;}const signature=r=>JSON.stringify([r.n.normalize('NFC').trim(),r.s,[...r.base].sort((a,b)=>a[0]-b[0])]);const seen=new Set();for(const entry of rows){const index=+entry.id.split(':')[2],row=G.J.items[10].list[index],key=signature(row);assert.ok(!seen.has(key),entry.n);seen.add(key);const matching=G.J.items[10].list.filter(r=>signature(r)===key);assert.equal(row.lvl,Math.min(...matching.map(r=>r.lvl)));const grant=createAdminGrant(bundle(),{slot:0,id:entry.id,quantity:1});assert.equal(grant.items[0].n,row.n);assert.equal(grant.items[0].lvl,row.lvl);}assert.equal(rows.filter(r=>r.n==='Liệt Hoàng Mã').length,1);assert.ok(rows.length>0);});
