import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { SCHEMA } from '../src/db.js';
import { cloudRoute,cleanBundle,passwordHash } from '../src/cloud-account.js';
import { auth as pvpAuth } from '../src/account.js';
import { GAME } from '../gen/game.js';
import { sha256Hex } from '../src/http.js';

function setup(){const sql=new DatabaseSync(':memory:');for(const query of SCHEMA)sql.exec(query);const DB={prepare(query){let args=[];return {bind(...values){args=values;return this},async first(){return sql.prepare(query).get(...args)||null},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:r.changes}}},async all(){return {results:sql.prepare(query).all(...args)}}}},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const q of statements)results.push(await q.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};return {env:{DB},sql};}
function request(path,method='POST',cookie='',origin='https://game.example'){return new Request('https://game.example/api/cloud/'+path,{method,headers:{origin,cookie}});}
async function route(env,path,body={},cookie='',method='POST'){const req=request(path,method,cookie);const result=await cloudRoute(req,env,body,new URL(req.url));return {data:await result.json(),cookie:result.headers.get('set-cookie')?.split(';')[0]||cookie};}
async function register(env,name='testuser'){return route(env,'register',{username:name,password:'password1234'});}
function bundle(level=10){const state=GAME.newSave();Object.assign(state,{fac:'kunlun',mode:'g2',lvl:level});return {v:1,slots:[state,null,null],shared:{jxidle_stash:{gold:30,items:[],mats:{}}}};}
const device='device_abcdefghijklmnop';

test('cloud: đăng ký, cookie bảo mật, đăng nhập và mật khẩu băm có salt',async()=>{const {env,sql}=setup();const a=await register(env);assert.equal(a.data.user.username,'testuser');assert.equal(a.data.recovery,undefined);const stored=sql.prepare('SELECT * FROM cloud_accounts').get();assert.notEqual(stored.password_hash,'password1234');assert.equal(stored.password_hash,await passwordHash('password1234',stored.password_salt,stored.password_iterations));const result=await cloudRoute(request('login'),env,{username:'TESTUSER',password:'password1234'},new URL('https://game.example/api/cloud/login'));const cookie=result.headers.get('set-cookie');for(const flag of ['HttpOnly','Secure','SameSite=Strict','Path=/api'])assert.ok(cookie.includes(flag));await assert.rejects(route(env,'login',{username:'testuser',password:'incorrect123'}),e=>e.code==='bad_credentials');await assert.rejects(register(env),e=>e.code==='username_taken');sql.close();});

test('cloud: cùng origin, chủ sở hữu và công tắc tắt',async()=>{const {env,sql}=setup();const a=await register(env);const bad=request('save','POST',a.cookie,'https://other.example');await assert.rejects(cloudRoute(bad,env,{},new URL(bad.url)),e=>e.code==='bad_origin');await assert.rejects(route(env,'load',{},'','GET'),e=>e.status===401);env.CLOUD_ACCOUNTS_ENABLED='0';await assert.rejects(route(env,'me',{},a.cookie,'GET'),e=>e.code==='cloud_disabled');await route(env,'logout',{},a.cookie);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM cloud_sessions').get().n,0);sql.close();});

test('cloud: ba ô, mọi chế độ, kho, bản trước, revision ngăn ghi đè và hai thiết bị',async()=>{const {env,sql}=setup(),a=await register(env);await route(env,'claim',{clientId:device},a.cookie);const one=bundle();one.slots[0].knb=7;one.slots[1]={...one.slots[0],mode:'ctc',lvl:90};one.slots[2]={...one.slots[0],mode:'phlt',lvl:120};const saved=await route(env,'save',{clientId:device,revision:0,bundle:one},a.cookie);assert.equal(saved.data.revision,1);const loaded=await route(env,'load',{},a.cookie,'GET');assert.equal(loaded.data.bundle.slots[1].lvl,90);assert.deepEqual(loaded.data.bundle.slots.map(s=>s.knb),[7,7,7]);assert.equal(loaded.data.bundle.shared.jxidle_stash.gold,30);await assert.rejects(route(env,'save',{clientId:device,revision:0,bundle:bundle()},a.cookie),e=>e.code==='save_conflict');const other='otherdevice_abcdefghijkl';await assert.rejects(route(env,'claim',{clientId:other},a.cookie),e=>e.code==='device_busy');await route(env,'claim',{clientId:other,takeover:true},a.cookie);await assert.rejects(route(env,'save',{clientId:device,revision:1,bundle:bundle(11)},a.cookie),e=>e.code==='device_changed');await route(env,'save',{clientId:other,revision:1,bundle:bundle(12)},a.cookie);const previous=await route(env,'load?previous=1',{},a.cookie,'GET');assert.equal(previous.data.bundle.slots[0].lvl,10);assert.equal(previous.data.bundle.slots[0].knb,7);assert.equal(previous.data.loadedRevision,1);const b=await register(env,'seconduser');assert.equal((await route(env,'load',{},b.cookie,'GET')).data.bundle,null);sql.close();});

test('cloud: lease hết hạn, heartbeat và cập nhật nguyên tử khi cùng revision',async()=>{const {env,sql}=setup(),a=await register(env);await route(env,'claim',{clientId:device},a.cookie);sql.prepare('UPDATE cloud_saves SET write_until=0').run();await assert.rejects(route(env,'heartbeat',{clientId:device},a.cookie),e=>e.code==='device_changed');await route(env,'claim',{clientId:device},a.cookie);await route(env,'heartbeat',{clientId:device},a.cookie);const results=await Promise.allSettled([route(env,'save',{clientId:device,revision:0,bundle:bundle(11)},a.cookie),route(env,'save',{clientId:device,revision:0,bundle:bundle(12)},a.cookie)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(sql.prepare('SELECT revision FROM cloud_saves').get().revision,1);sql.close();});

test('cloud: không có API khôi phục; đăng xuất và hết hạn phiên không xóa tiến trình',async()=>{const {env,sql}=setup(),a=await register(env);await route(env,'claim',{clientId:device},a.cookie);await route(env,'save',{clientId:device,revision:0,bundle:bundle()},a.cookie);await assert.rejects(route(env,'recover',{username:'testuser',password:'newpassword123'},a.cookie),e=>e.status===404);await route(env,'logout',{},a.cookie);await assert.rejects(route(env,'me',{},a.cookie,'GET'),e=>e.code==='cloud_login');const login=await route(env,'login',{username:'testuser',password:'password1234'});assert.equal((await route(env,'load',{},login.cookie,'GET')).data.bundle.slots[0].lvl,10);sql.prepare('UPDATE cloud_sessions SET expires_at=0').run();await assert.rejects(route(env,'me',{},login.cookie,'GET'),e=>e.code==='cloud_login');sql.close();});

test('cloud: không truyền bí mật, sandbox, chế độ/nhân vật sai hoặc dữ liệu quá lớn',()=>{const b=bundle();b.slots[0].token='secret';b.slots[0].online={id:'old',token:'private'};b.slots[0].admin=true;const clean=cleanBundle(b);assert.equal(clean.slots[0].token,undefined);assert.equal(clean.slots[0].online.token,undefined);assert.equal(clean.slots[0].admin,undefined);assert.equal(clean.slots[0].snd,undefined);assert.throws(()=>cleanBundle({...b,slots:[]}),e=>e.code==='bad_save');assert.throws(()=>cleanBundle({...b,slots:[{...b.slots[0],mode:'other'},null,null]}),e=>e.code==='bad_save');b.slots[0].name='x'.repeat(1000000);assert.throws(()=>cleanBundle(b),e=>e.code==='save_too_large');});

test('cloud: liên kết PvP giữ tài khoản cũ, không đưa token vào snapshot',async()=>{const {env,sql}=setup(),a=await register(env),token='original_pvp_token_1234567890';sql.prepare('INSERT INTO accounts(id,token_hash,name,created_at) VALUES(?,?,?,?)').run('pvp1',await sha256Hex(token),'PvP cũ',Date.now());const b=bundle();b.slots[0].mode='ctc';b.slots[0].online={id:'pvp1',name:'PvP cũ'};await route(env,'claim',{clientId:device},a.cookie);await route(env,'save',{clientId:device,revision:0,bundle:b},a.cookie);await route(env,'link-pvp',{links:[{slot:0,token}]},a.cookie);const req=new Request('https://game.example/api/me',{headers:{cookie:a.cookie,'x-cloud-slot':'0'}});assert.equal((await pvpAuth(req,env)).id,'pvp1');const valid=new Request('https://game.example/api/sync',{method:'POST',headers:{cookie:a.cookie,'x-cloud-slot':'0','x-cloud-device':device,origin:'https://game.example'}});assert.equal((await pvpAuth(valid,env)).id,'pvp1');const oldDevice=new Request('https://game.example/api/sync',{method:'POST',headers:{cookie:a.cookie,'x-cloud-slot':'0','x-cloud-device':'wrongdevice_123456',origin:'https://game.example'}});await assert.rejects(pvpAuth(oldDevice,env),e=>e.code==='device_changed');const bad=new Request('https://game.example/api/sync',{method:'POST',headers:{cookie:a.cookie,'x-cloud-slot':'0',origin:'https://other.example'}});await assert.rejects(pvpAuth(bad,env),e=>e.code==='bad_origin');sql.close();});

test('cloud: tên và mật khẩu đúng bốn ký tự được chấp nhận, ba ký tự bị từ chối',async()=>{const {env,sql}=setup();const a=await route(env,'register',{username:'abcd',password:'1234'});assert.ok(a.data.user.id);await route(env,'login',{username:'abcd',password:'1234'});await assert.rejects(route(env,'register',{username:'abc',password:'1234'}),e=>e.code==='bad_username');await assert.rejects(route(env,'register',{username:'abcde',password:'123'}),e=>e.code==='bad_password');sql.close();});
