import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
const source=fs.readFileSync('js/cloud-account.js','utf8');
function setup(){const values=new Map(),session=new Map(),nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{id,classList:{add(){},remove(){}},value:id==='cloudUsername'?'tester':'testpass',textContent:'Đăng nhập',disabled:false});return nodes.get(id)};const c={crypto:webcrypto,Uint8Array,console,Date,performance:{now:()=>100},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},sessionStorage:{getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)},S:{fac:null},SLOT:0,SAVE_LOCK:false,lastT:0,document:{hidden:false,getElementById:node,querySelectorAll:()=>[],activeElement:null},esc:String};vm.createContext(c);vm.runInContext(source.slice(0,source.indexOf('(function(){const panel')),c);c.cloudShow=html=>c.html=html;c.cloudClose=()=>c.closed=true;c.cloudInjectButtons=()=>{};c.cloudStatus=()=>{};c.cloudCapture=()=>({v:1,slots:[null,null,null],shared:{}});return{c,node,values,session,C:vm.runInContext('CLOUD',c),entry:()=>vm.runInContext('cloudEntryPending',c)};}
test('new visitor sees login/register/guest choices and guest selection releases entry gate',async()=>{const t=setup();t.c.cloudBootstrap=async()=>{};await t.c.cloudStartup();assert.match(t.c.html,/id="cloudAuthSubmit"/);assert.match(t.c.html,/id="cloudAuthSwitch"/);assert.match(t.c.html,/Chơi ngay · không cần tài khoản/);assert.equal(t.entry(),true);t.node('cloudGuestPlay').onclick();assert.equal(t.entry(),false);assert.equal(t.c.closed,true);assert.equal(t.session.get('jxidle_cloud_guest_entry'),'1');assert.equal(t.C.ready,false);});
test('new empty account enters character creation without uploading another local character',async()=>{const t=setup();t.C.user={id:'u'};t.c.cloudApi=async()=>({hasSave:false,revision:0});t.c.cloudClaim=async()=>({revision:0});t.c.cloudInstall=(b,slot)=>t.c.installed={b,slot};await t.c.cloudEnterAccount();assert.deepEqual(JSON.parse(JSON.stringify(t.c.installed.b)),{v:1,slots:[null,null,null],shared:{}});assert.equal(t.c.installed.slot,null);});
test('existing account or local guest character requires save selection',async()=>{for(const remoteSave of [false,true]){const t=setup();t.c.cloudApi=async()=>({hasSave:remoteSave});t.c.cloudCapture=()=>({slots:[{fac:'shaolin'},null,null]});t.c.cloudAccountMenu=async()=>t.c.selected=true;t.c.cloudInstall=()=>{throw Error('must not overwrite')};await t.c.cloudEnterAccount();assert.equal(t.c.selected,true);}});
test('valid returning session resumes only when its save is ready and not paused',async()=>{const t=setup();t.c.cloudBootstrap=async()=>{t.C.user={id:'u'};t.C.ready=true};await t.c.cloudStartup();assert.equal(t.entry(),false);assert.equal(t.c.closed,true);const other=setup();other.c.cloudBootstrap=async()=>{other.C.user={id:'u'};other.C.ready=true;other.C.paused=true};other.c.cloudEnterAccount=async()=>other.c.selection=true;await other.c.cloudStartup();assert.equal(other.entry(),true);assert.equal(other.c.selection,true);});
test('30-second scheduler syncs ready authenticated sessions, skips guests and entry gate',async()=>{const t=setup();t.c.setInterval=(fn,ms)=>{t.c.interval={fn,ms}};const start=source.indexOf('setInterval(()=>{if(document.hidden||cloudEntryPending)');const end=source.indexOf("document.addEventListener('visibilitychange'",start);vm.runInContext(source.slice(start,end),t.c);assert.equal(t.c.interval.ms,30000);let count=0;t.c.cloudSync=()=>count++;t.c.interval.fn();assert.equal(count,0);t.c.cloudGuestPlay();t.c.interval.fn();assert.equal(count,0);t.C.user={id:'u'};t.C.ready=true;t.c.interval.fn();assert.equal(count,1);t.c.document.hidden=true;t.c.interval.fn();assert.equal(count,1);});
test('guest selection during login does not allow late login response to change active account',async()=>{const t=setup();let resolve;t.c.cloudApi=()=>new Promise(r=>resolve=r);t.c.cloudError=()=>{};t.c.cloudEnterAccount=()=>{throw Error('late response must be ignored')};await t.c.cloudAuthForm();const request=t.node('cloudAuthForm').onsubmit({preventDefault(){}});t.c.cloudGuestPlay();resolve({user:{id:'late'}});await request;assert.equal(t.C.user,null);assert.equal(t.entry(),false);});
test('guest can enter immediately while startup authentication request is still pending',async()=>{const t=setup();let release;t.c.cloudBootstrap=()=>new Promise(r=>release=r);const startup=t.c.cloudStartup();assert.match(t.c.html,/Chơi ngay · không cần tài khoản/);t.node('cloudGuestPlay').onclick();assert.equal(t.entry(),false);release();await startup;assert.equal(t.entry(),false);assert.equal(t.c.closed,true);});
