import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
function setup(){let code=fs.readFileSync('worker/gen/game.js','utf8').replace('export const GAME','const GAME');code=code.replace('return {\n  setS',fs.readFileSync('js/gear_policy.js','utf8')+'\n'+fs.readFileSync('js/ui.js','utf8')+'\nreturn {lootFilter,lootMatch,lootWanted,lootPreset,lootCriteriaChanged,sellUnmatched,roomCandidate,makeRoom,bestEquipPlan,isJunk,addItem,sweepJunk,updateGround,pickUp,R,H,\n  setS');const elements={fPickMode:{value:'all'}},c={crypto:webcrypto,console,document:{getElementById:id=>elements[id]||null},tagItem(){},questTick(){},jrAdd(){},manual:()=>false};vm.createContext(c);vm.runInContext(code,c);const G=vm.runInContext('GAME',c),s=G.newSave();s.fac='shaolin';s.mode='g2';s.autoEquip=false;s.autoJunk=true;s.lootF={minRar:1,minLvl:1,groups:[],series:[],rules:[],auto:true,pickMode:'filter',ruleMode:'any'};G.setS(s);vm.runInContext('bestEquipPlan=()=>({gain:0,slot:"armor"});itemPower=it=>it.power||1;sexOk=()=>true;reqOk=()=>true;isKept=()=>false;itemValue=()=>10;',c);return{G,s,c,elements};}
const item=(more={})=>({uid:'item',d:2,k:0,lvl:5,r:1,s:0,n:'Áo Thiên Sơn',base:[],mag:[],ext:[],power:1,...more});
test('filter combines rarity, item level, name and series; attributes obey any/all',()=>{const{G,s}=setup();Object.assign(s.lootF,{minRar:2,minLvl:5,kw:'thien son',series:[0]});assert.equal(G.lootMatch(item({r:2})),true);for(const more of [{r:1},{r:2,lvl:4},{r:2,s:1},{r:2,n:'Áo khác'}])assert.equal(G.lootMatch(item(more)),false);const data=vm.runInNewContext(fs.readFileSync('data.js','utf8')+';window.JX',{window:{}}),life=Object.keys(data.attr).find(k=>data.attr[k]==='lifemax_v'),mana=Object.keys(data.attr).find(k=>data.attr[k]==='manamax_v');Object.assign(s.lootF,{rules:[{attr:'lifemax_v',min:100},{attr:'manamax_v',min:50}]});const it=item({r:2,mag:[{a:+life,p:[120,0,0]}]});assert.equal(G.lootMatch(it),true);s.lootF.ruleMode='all';assert.equal(G.lootMatch(it),false);it.mag.push({a:+mana,p:[60,0,0]});assert.equal(G.lootMatch(it),true);});
test('matching automatic pickup is retained even if weaker than equipped item, including subsequent cleanup',()=>{const{G,s}=setup();s.lootF.kw='thien son';s.eq.armor=item({uid:'equipped',power:100});const it=item();assert.equal(G.isJunk(it),false);assert.equal(G.addItem(it,true,true,false),true);assert.ok(s.inv.includes(it));assert.equal(G.sweepJunk(),0);assert.ok(s.inv.includes(it));assert.equal(s.gold,0);});
test('wild enemies for distant bots never block auto pickup after player wave is clear',()=>{const{G,s}=setup();const it=item();G.H.x=100;G.H.y=100;G.R.enemies=[{botWild:true,dead:false}];G.R.ground=[{it,x:100,y:100,age:1}];assert.equal(G.updateGround(.1),true);assert.equal(G.R.ground.length,0);assert.ok(s.inv.includes(it));});
test('live player-wave enemy still blocks automatic pickup and mismatched loot remains on ground',()=>{const{G,s}=setup();G.H.x=100;G.H.y=100;G.R.ground=[{it:item(),x:100,y:100,age:1}];G.R.enemies=[{dead:false}];assert.equal(G.updateGround(.1),false);assert.equal(G.R.ground.length,1);G.R.enemies=[];s.lootF.minRar=3;assert.equal(G.updateGround(.1),false);assert.equal(G.R.ground.length,1);s.lootF.pickMode='all';assert.equal(G.updateGround(.1),true);assert.equal(s.inv.length,0);assert.equal(s.gold,10);});
test('attribute presets and edits activate the filter instead of silently retaining pick-all mode',()=>{const{G,s,elements}=setup();s.lootF.pickMode='all';G.lootPreset('survival');assert.equal(s.lootF.pickMode,'filter');assert.ok(s.lootF.rules.length>0);s.lootF.pickMode='all';G.lootCriteriaChanged();assert.equal(s.lootF.pickMode,'filter');assert.equal(elements.fPickMode.value,'filter');});
test('game UI keeps a focused filter input intact, then refreshes dirty inventory after blur',()=>{const code=fs.readFileSync('js/main.js','utf8'),frame=code.slice(code.indexOf('function frame(now)'),code.indexOf('const AUTOSAVE_MS'));let renders=0;const c={lastT:0,uiT:.2,saveT:0,autoT:0,drawAcc:0,AUTOSAVE_MS:900000,invDirty:true,inventoryFilters:true,curTab:'inv',S:{fac:'shaolin'},R:{},window:{JXAFK:true},document:{hidden:false,activeElement:{closest:()=>({id:'fKw'})}},gameSpeed:()=>1,guard:(_,f)=>f(),gamepadPoll(){},simulateFrame(){},modeFrame(){},updateTop(){},updatePadCd(){},renderInv(){renders++},requestAnimationFrame(){}};vm.createContext(c);vm.runInContext(frame,c);c.frame(200);assert.equal(renders,0);c.document.activeElement=null;c.frame(400);assert.equal(renders,1);});
test('automatic pickup remains disabled when switched off or playing manually',()=>{const{G,s,c}=setup();G.R.enemies=[];G.H.x=100;G.H.y=100;G.R.ground=[{it:item(),x:100,y:100,age:1}];s.lootF.auto=false;assert.equal(G.updateGround(.1),false);s.lootF.auto=true;c.manual=()=>true;assert.equal(G.updateGround(.1),false);assert.equal(G.R.ground.length,1);});

test("auto sale and manual filtered sale agree even in pick-all mode and near-strength gear",()=>{for(const auto of [true,false]){const {G,s}=setup();s.lootF.pickMode="all";s.lootF.kw="thien son";s.eq.armor=item({uid:99,power:100});const matching=item({uid:1,power:1}),rejected=item({uid:2,n:"Áo khác",power:90});s.inv=[matching,rejected];if(auto)assert.equal(G.sweepJunk(),1);else assert.equal(G.sellUnmatched().n,1);assert.equal(s.inv.length,1);assert.equal(s.inv[0].uid,1);assert.equal(s.gold,10);}});
test("capacity replacement protects rarity/name/series matches, without requiring attribute rules",()=>{const {G,s}=setup();s.lootF.minRar=2;const matching=item({uid:1,r:2,power:1}),rejected=item({uid:2,r:1,power:2});s.inv=[matching,rejected];assert.equal(G.roomCandidate(item({r:2,power:50})).uid,2);s.inv=[matching];assert.equal(G.roomCandidate(item({r:2,power:50})),null);s.autoJunk=false;s.inv=[rejected];assert.equal(G.makeRoom(item({r:2,power:50})),false);assert.equal(s.gold,0);});
test("disabled auto sale keeps unmatched items and sweep never sells protected upgrades",()=>{const {G,s,c}=setup();s.lootF.kw="thien son";s.autoJunk=false;s.inv=[item({n:"Khác"})];assert.equal(G.sweepJunk(),0);assert.equal(s.inv.length,1);s.autoJunk=true;const upgrade=G.makeItem(2,0,1,1);s.inv=[upgrade];assert.ok(G.bestEquipPlan(upgrade).gain>.01);assert.equal(G.sweepJunk(),0);assert.equal(G.sellUnmatched().n,0);});

test("full inventory with auto sale disabled does not repeatedly chase unpickable loot",()=>{const {G,s}=setup();s.autoJunk=false;s.inv=Array.from({length:1000},(_,uid)=>item({uid,n:"Khác"}));G.R.enemies=[];G.H.x=100;G.H.y=100;G.R.ground=[{it:item(),x:100,y:100,age:1}];assert.equal(G.updateGround(.1),false);assert.equal(G.R.ground.length,1);assert.equal(s.gold,0);});
