import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../../',import.meta.url),ctx={window:{},setInterval(){},setTimeout(){},img:f=>({complete:true,naturalWidth:1,f}),mountWeaponType:s=>s.eq.weapon?.k||-1};vm.createContext(ctx);for(const file of ['js/doll-data.js','js/doll.js','js/mount-rig-data.js','js/mount-rig.js'])vm.runInContext(fs.readFileSync(new URL(file,root),'utf8'),ctx);
const state=(k=0,sex=0)=>({sex,eq:{horse:{d:10,k,lvl:1}}});
test('shop horse types resolve nine distinct client models and change immediately on equip',()=>{const models=new Set(),sources=new Set(),s=state();for(let k=0;k<=8;k++){s.eq.horse={d:10,k,lvl:1};const p=ctx.clientRidePlan(s,'run');assert.ok(p,'shop horse '+k);models.add(p.kind);sources.add(p.layers[12]);}assert.equal(models.size,9);assert.equal(sources.size,9);assert.equal(ctx.clientRidePlan(state(0),'st').kind,8);assert.equal(ctx.clientRidePlan(state(1),'st').kind,4);});
test('men and women use original seated body, hands and head for stand, walk and run',()=>{for(const sex of [0,1])for(const act of ['st','walk','run']){const p=ctx.clientRidePlan(state(0,sex),act);assert.ok(p);assert.ok(p.body.source.includes(sex?'woman':'man'));assert.match(p.body.source,act==='run'?/_HR01\.spr$/i:act==='walk'?/_HW01\.spr$/i:/_RD01\.spr$/i);assert.ok(p.layers[0]&&p.layers[6]&&p.layers[7]);}});
test('native riding uses one scale and origin for rider and horse, no stretched foot sprites',()=>{const calls=[],c={save(){},restore(){},beginPath(){},ellipse(){},fill(){},drawImage(...a){calls.push(a)}};const s=state(),p=ctx.clientRidePlan(s,'run');assert.ok(ctx.drawClientRiding(c,100,100,'run',2,.3,1/.6,1,s)>0);assert.ok(calls.length>=8);for(const a of calls){const sheet=Object.values(ctx.window.JMRIG.sheets).find(x=>x.f===a[0].f);assert.ok(Math.abs(a[7]/a[3]-.8)<1e-9);assert.ok(Math.abs(a[8]/a[4]-.8)<1e-9);assert.ok(Math.abs(a[5]+sheet.ax*.8-100)<1e-9);assert.ok(Math.abs(a[6]+sheet.ay*.8-100)<1e-9);}assert.ok(calls.some(a=>a[0].f===p.body.f));});
test('directional layer order matches client RideRun Dir5, pending sprites draw no partial rig',()=>{const p=ctx.clientRidePlan(state(),'run');assert.deepEqual(Array.from(ctx.clientRideOrder(p,4,0)),[12,13,8,6,5,14,16,0,9,7,4,1]);const saved=ctx.img;ctx.img=()=>({complete:false,naturalWidth:0});assert.equal(ctx.drawClientRiding({},0,0,'run',0,0,1,1,state()),null);ctx.img=saved;});
test('all imported riding atlases have correct dimensions, frame samples and provenance',()=>{for(const s of Object.values(ctx.window.JMRIG.sheets)){const b=fs.readFileSync(new URL(s.f,root));assert.equal(b.readUInt32BE(16),s.w*s.n);assert.equal(b.readUInt32BE(20),s.h*s.d);assert.ok(s.source&&s.pak&&s.hash);}});
test('sampled rider frame drives the original horse frame instead of independent atlas clocks',()=>{const rider={n:8,per:10,frames:[0,1,2,3,5,6,7,8]},horse={n:10};for(let col=0;col<8;col++){const phase=rider.frames[col]/rider.per;assert.equal(ctx.clientRideColumn(rider,phase),col);assert.equal(ctx.clientRideColumn(horse,phase),rider.frames[col]);}});
