import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const source=fs.readFileSync('js/jxorig.js','utf8');
function layout(w,h,tab="char"){const styles={},app={clientWidth:w,clientHeight:h},panel={style:{setProperty(k,v){styles[k]=v}},classList:{contains:()=>false,toggle(){}},dataset:{}},c={window:{},location:{search:''},URLSearchParams,localStorage:{getItem:()=>null},$:s=>s==='#app'?app:s==='#panel'?panel:null,on:true,curTab:tab,skillPanelPos:null,WIN:{char:{w:428,h:430,x:20,y:150},skill:{w:205,h:376,x:338,y:108}},charPanelPos:null,charInventoryOpen:false,closeCharInventory(){},charDetailsOpen:false};vm.createContext(c);vm.runInContext(source.slice(source.indexOf('function pref'),source.indexOf('function apply')),c);c.place();return{c,styles};}
test('native character window fits touch Safari portrait and landscape without desktop pointer gate',()=>{for(const [w,h] of [[390,844],[844,390],[768,1024]]){const{c,styles}=layout(w,h);assert.equal(c.wantOn(),true);assert.ok(parseFloat(styles['--jxw'])<=w-8);assert.ok(parseFloat(styles['--jxh'])<=h-92);assert.ok(Number(styles['--jxscale'])>0);}});
test('desktop character window retains original PC dimensions',()=>{const{c,styles}=layout(1366,800);assert.equal(c.wantOn(),true);assert.equal(styles['--jxscale'],'1');assert.equal(styles['--jxw'],'428px');assert.equal(styles['--jxh'],'430px');});
test('blocked gamepad API is probed once and never triggers repeated game loop failures',()=>{const s=fs.readFileSync('js/control.js','utf8');let calls=0;const c={navigator:{getGamepads(){calls++;throw new Error('SecurityError')}},GP:{v:[1,1],prev:[true]},console:{warn(){}},S:{fac:null}};vm.createContext(c);vm.runInContext(s.slice(s.indexOf('let gamepadUnavailable'),s.indexOf('function inputVec')),c);for(let i=0;i<120;i++)assert.doesNotThrow(()=>c.gamepadPoll());assert.equal(calls,1);assert.deepEqual(Array.from(c.GP.v),[0,0]);});
test('working gamepad API remains active on subsequent frames',()=>{const s=fs.readFileSync('js/control.js','utf8');let calls=0;const c={navigator:{getGamepads(){calls++;return[{connected:true,axes:[0,0],buttons:[]}]}},GP:{v:[0,0],prev:[]},S:{fac:null}};vm.createContext(c);vm.runInContext(s.slice(s.indexOf('let gamepadUnavailable'),s.indexOf('function inputVec')),c);c.gamepadPoll();c.gamepadPoll();assert.equal(calls,2);});

test('native skill window fits Safari portrait and landscape with PC grid dimensions',()=>{for(const[w,h]of [[390,844],[844,390],[768,1024]]){const{styles}=layout(w,h,'skill');assert.ok(parseFloat(styles['--jxw'])<=w-8);assert.ok(parseFloat(styles['--jxh'])<=h-100);assert.ok(parseFloat(styles['--jxt'])+parseFloat(styles['--jxh'])<=h-4);assert.ok(Number(styles['--jxscale'])>0);}});
