import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {SCHEMA} from '../src/db.js';
import {cloudRoute} from '../src/cloud-account.js';
import {GAME as G} from '../gen/game.js';
const device='economy_device_abcdefghijklmnop';
function setup(){const sql=new DatabaseSync(':memory:');for(const q of SCHEMA)sql.exec(q);sql.exec("ALTER TABLE chars ADD COLUMN power INTEGER NOT NULL DEFAULT 0; ALTER TABLE chars ADD COLUMN bracket TEXT; ALTER TABLE chars ADD COLUMN flagged INTEGER NOT NULL DEFAULT 0");let tail=Promise.resolve();const DB={prepare(q){let args=[];return {bind(...v){args=v;return this;},async first(){return sql.prepare(q).get(...args)||null;},async all(){return {results:sql.prepare(q).all(...args)};},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}};}};},batch(list){const job=tail.then(async()=>{sql.exec('BEGIN');try{const results=[];for(const q of list)results.push(await q.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}});tail=job.catch(()=>{});return job;}};return {sql,env:{DB}};}
async function route(env,path,body={},cookie='',method='POST'){const req=new Request('https://game.example/api/cloud/'+path,{method,headers:{origin:'https://game.example',cookie}});const r=await cloudRoute(req,env,body,new URL(req.url));return {data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
function saved(sql,id){return JSON.parse(sql.prepare('SELECT snapshot FROM cloud_saves WHERE account_id=?').get(id).snapshot);}
function body(revision,extra={}){return {clientId:device,requestId:crypto.randomUUID(),revision,slot:0,controls:{running:false},...extra};}
async function legacy(env,name='econuser',mode='g2'){const a=await route(env,'register',{username:name,password:'password1234'});await route(env,'claim',{clientId:device},a.cookie);const s=G.economyEngine.create({fac:'shaolin',mode,name,cid:crypto.randomUUID()});Object.assign(s,{gold:1e8,knb:200,lvl:80,autoEquip:false,autoJunk:false,autoBuy:false,autoForge:false});await route(env,'save',{clientId:device,revision:0,bundle:{v:1,slots:[s,null,null],shared:{}}},a.cookie);return a;}
test('existing account baseline is backed up once, uploaded money/items cannot replace it',async()=>{const {env,sql}=setup(),a=await legacy(env);const baseline=saved(sql,a.data.user.id);env.SERVER_ECONOMY_ENABLED='1';const me=await route(env,'me',{},a.cookie,'GET');assert.equal(me.data.economyVersion,1);const forged=structuredClone(baseline);forged.slots[0].gold=9e14;forged.slots[0].knb=9e9;forged.slots[0].inv=[{uid:999,n:'Fake'}];const r=await route(env,'save',body(1,{bundle:forged}),a.cookie);assert.equal(r.data.patch.slots[0].state.gold,1e8);assert.equal(r.data.patch.slots[0].state.knb,200);assert.deepEqual(r.data.patch.slots[0].state.inv,baseline.slots[0].inv);const backup=JSON.parse(sql.prepare('SELECT snapshot FROM economy_backups WHERE account_id=?').get(a.data.user.id).snapshot);assert.deepEqual(backup,baseline);await route(env,'save',body(2),a.cookie);assert.equal(sql.prepare('SELECT COUNT(*) n FROM economy_backups').get().n,1);await assert.rejects(route(env,'economy/backup',{},a.cookie,'GET'),e=>e.code==='admin_only');sql.close();});
test('new secure account creates native starter, ignores imported gold, items and level',async()=>{const {env,sql}=setup();env.SERVER_ECONOMY_ENABLED='1';const a=await route(env,'register',{username:'newsecure',password:'password1234'});await route(env,'claim',{clientId:device},a.cookie);const r=await route(env,'save',body(0,{characters:[{fac:'shaolin',mode:'ctc',name:'Fresh',cid:crypto.randomUUID(),lvl:180,gold:1e15,knb:10000,inv:[{uid:111}]}]}),a.cookie);const s=r.data.patch.slots[0].state;assert.equal(s.lvl,1);assert.equal(s.knb||0,0);assert.notEqual(s.gold,1e15);assert.ok(s.eq.weapon);assert.ok(s.eq.weapon.eid);assert.ok(s.inv.every(it=>it.uid!==111));sql.close();});
test('shop uses server catalogue and balances; transaction replay and concurrent revision grant once',async()=>{const {env,sql}=setup(),a=await legacy(env);env.SERVER_ECONOMY_ENABLED='1';await route(env,'me',{},a.cookie,'GET');const buy=body(1,{action:'buyGoods',args:['weapon',0],price:0});const one=await route(env,'economy/action',buy,a.cookie),s=one.data.patch.slots[0].state;assert.equal(s.inv.length,1);assert.ok(s.gold<1e8);const repeat=await route(env,'economy/action',buy,a.cookie);assert.equal(repeat.data.replayed,true);assert.equal(saved(sql,a.data.user.id).slots[0].inv.length,1);const requests=[body(2,{action:'buyTienThaoLo'}),body(2,{action:'buyTienThaoLo'})];const results=await Promise.allSettled(requests.map(b=>route(env,'economy/action',b,a.cookie)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(saved(sql,a.data.user.id).slots[0].knb,198);assert.equal(sql.prepare('SELECT COUNT(*) n FROM economy_ledger').get().n,2);sql.close();});
test('stash deposit/withdraw conserves money and item, changing uploaded stash cannot mint',async()=>{const {env,sql}=setup(),a=await legacy(env);env.SERVER_ECONOMY_ENABLED='1';await route(env,'me',{},a.cookie,'GET');await route(env,'economy/action',body(1,{action:'stashGold',args:['in',100000]}),a.cookie);let b=saved(sql,a.data.user.id);assert.equal(b.slots[0].gold+b.shared.jxidle_stash.gold,1e8);await route(env,'economy/action',body(2,{action:'stashGold',args:['out',100000]}),a.cookie);b=saved(sql,a.data.user.id);assert.equal(b.slots[0].gold,1e8);assert.equal(b.shared.jxidle_stash.gold,0);await assert.rejects(route(env,'economy/action',body(3,{action:'stashGold',args:['out',1]}),a.cookie),e=>e.code==='economy_action');sql.close();});
test('elapsed time comes from persisted server checkpoint; x10 and fake point budgets rejected',async()=>{const {env,sql}=setup(),a=await legacy(env);env.SERVER_ECONOMY_ENABLED='1';await route(env,'me',{},a.cookie,'GET');await route(env,'save',body(1,{controls:{running:true,speed:2}}),a.cookie);const meta=JSON.parse(sql.prepare('SELECT meta_json FROM economy_states').get().meta_json);meta.settledAt=Date.now()-30000;sql.prepare('UPDATE economy_states SET meta_json=?').run(JSON.stringify(meta));const r=await route(env,'save',body(2,{controls:{running:false},elapsed:1e15,kills:1e12,last:0}),a.cookie);assert.ok(r.data.reward.kills>=0&&r.data.reward.kills<=180);await assert.rejects(route(env,'save',body(3,{controls:{speed:10}}),a.cookie),e=>e.code==='economy_action');await assert.rejects(route(env,'save',body(3,{controls:{attr:{str:999999}}}),a.cookie),e=>e.code==='economy_action');assert.equal(sql.prepare('SELECT revision FROM cloud_saves').get().revision,3);sql.close();});
test('negative Huyen Tinh purchase cannot credit money; invalid action is atomic',async()=>{const {env,sql}=setup(),a=await legacy(env);env.SERVER_ECONOMY_ENABLED='1';await route(env,'me',{},a.cookie,'GET');await assert.rejects(route(env,'economy/action',body(1,{action:'buyHT',args:[1,-5]}),a.cookie),e=>e.code==='economy_action');assert.equal(saved(sql,a.data.user.id).slots[0].gold,1e8);assert.equal(sql.prepare('SELECT COUNT(*) n FROM economy_requests').get().n,0);sql.close();});

test('secure market ignores forged balance and delivers the escrowed item once',async()=>{const {env,sql}=setup(),a=await legacy(env,'secureseller'),b=await legacy(env,'securebuyer');const as=saved(sql,a.data.user.id);G.setS(as.slots[0]);const it=G.makeItem(0,0,1,0);as.slots[0].inv.push(it);await route(env,'save',{clientId:device,revision:1,bundle:as},a.cookie);env.SERVER_ECONOMY_ENABLED='1';await route(env,'me',{},a.cookie,'GET');await route(env,'me',{},b.cookie,'GET');const post=await route(env,'market/post',{...body(2),uid:it.uid,currency:'knb',price:5,bundle:{fake:true}},a.cookie);const id=sql.prepare("SELECT id FROM market_listings").get().id;const buy=await route(env,'market/buy',{...body(1),id,bundle:{fake:true}},b.cookie);assert.equal(saved(sql,b.data.user.id).slots[0].knb,195);assert.equal(saved(sql,b.data.user.id).slots[0].inv.length,1);assert.equal(saved(sql,a.data.user.id).slots[0].inv.length,0);await assert.rejects(route(env,'market/buy',{...body(buy.data.revision),id},b.cookie));sql.close();});
test('offline catchup is capped and cannot be repeated with another request ID',async()=>{const {env,sql}=setup(),a=await legacy(env);env.SERVER_ECONOMY_ENABLED='1';await route(env,'me',{},a.cookie,'GET');const id=a.data.user.id,m=JSON.parse(sql.prepare('SELECT meta_json FROM economy_states WHERE account_id=?').get(id).meta_json);m.settledAt=Date.now()-20*86400000;m.running=true;sql.prepare('UPDATE economy_states SET meta_json=? WHERE account_id=?').run(JSON.stringify(m),id);const r=await route(env,'save',body(1),a.cookie);const first=saved(sql,id).slots[0];assert.ok(first.gold>1e8);assert.ok(JSON.parse(sql.prepare('SELECT meta_json FROM economy_states WHERE account_id=?').get(id).meta_json).offSec<=8*3600);await route(env,'save',body(r.data.revision),a.cookie);assert.equal(saved(sql,id).slots[0].gold,first.gold);sql.close();});

test('online registration/link uses the secure character and sync ignores forged level',async()=>{const {env,sql}=setup(),a=await legacy(env,'onlineowner','ctc');env.SERVER_ECONOMY_ENABLED='1';await route(env,'me',{},a.cookie,'GET');const original=saved(sql,a.data.user.id).slots[0];original.lvl=20;sql.prepare('UPDATE cloud_saves SET snapshot=? WHERE account_id=?').run(JSON.stringify({v:1,slots:[original,null,null],shared:{}}),a.data.user.id);const {register,sync,auth}=await import('../src/account.js');const req=new Request('https://game.example/api/register',{method:'POST',headers:{origin:'https://game.example',cookie:a.cookie}});const forged=structuredClone(original);forged.lvl=39;forged.gold=1e14;const pvp=await register(req,env,{name:'Secure Online',save:forged});assert.equal(JSON.parse(sql.prepare('SELECT snapshot FROM chars WHERE account_id=?').get(pvp.id).snapshot).lvl,20);await route(env,'link-pvp',{links:[{slot:0,token:pvp.token}]},a.cookie);const linked=new Request('https://game.example/api/sync',{method:'POST',headers:{origin:'https://game.example',cookie:a.cookie,'x-cloud-slot':'0','x-cloud-device':device}});assert.equal((await auth(linked,env)).id,pvp.id);forged.lvl=180;await sync(linked,env,{save:forged});assert.equal(sql.prepare('SELECT lvl FROM chars WHERE account_id=?').get(pvp.id).lvl,20);sql.close();});

test('clear inventory deletes every unlocked item regardless of filter, keeps locks/equipment, grants no currency',async()=>{const {env,sql}=setup(),a=await legacy(env);const b=saved(sql,a.data.user.id),s=b.slots[0];G.setS(s);const ordinary=G.makeItem(0,0,1,0),rare=G.makeItem(2,0,1,5),locked=G.makeItem(2,0,1,1);locked.locked=true;s.inv=[ordinary,rare,locked];s.lootF={kw:'anything',minRar:5,pickMode:'all'};const eq=structuredClone(s.eq);await route(env,'save',{clientId:device,revision:1,bundle:b},a.cookie);env.SERVER_ECONOMY_ENABLED='1';await route(env,'me',{},a.cookie,'GET');const r=await route(env,'economy/action',body(2,{action:'clearInventory'}),a.cookie);const after=saved(sql,a.data.user.id).slots[0];assert.equal(r.data.result.n,2);assert.equal(after.inv.length,1);assert.equal(after.inv[0].uid,locked.uid);assert.ok(after.inv[0].locked);assert.deepEqual(Object.values(after.eq).map(it=>it?.uid),Object.values(eq).map(it=>it?.uid));assert.equal(after.gold,s.gold);assert.equal(after.knb,s.knb);sql.close();});
