import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {SocialRoom} from '../src/social-room.js';import worker from '../src/index.js';
function setup(){const db=new DatabaseSync(':memory:');let writes=0,reads=0;const sockets=[];const ctx={storage:{sql:{exec(q,...args){if(!/^SELECT/i.test(q))writes++;if(q.includes(';')){db.exec(q);return {toArray:()=>[]}}const rows=db.prepare(q).all(...args);return {toArray:()=>rows}}}},getWebSockets:()=>sockets};const env={DB:{prepare(q){reads++;return {bind(){return this},async first(){assert.match(q,/cloud_sessions/);return {account_id:'same-account'}},async all(){return {results:[{id:20,name:'Old',sender:'old-sender',text:'History',at:Date.now()}]}}}}}};return {db,ctx,env,sockets,room:new SocialRoom(ctx,env),writes:()=>writes,reads:()=>reads};}
const guest='guest_abcdefghijklmnop',tab='tab_abcdefghijklmnop';function req(path,body,cookie=''){return new Request('https://game.example/api/'+path,{method:body?'POST':'GET',headers:{origin:'https://game.example','cf-connecting-ip':'127.0.0.1',cookie},body:body?JSON.stringify(body):undefined})}
test('presence heartbeats and leave use zero SQL writes; expired tabs are not counted',async()=>{const x=setup(),w=x.writes();let r=await x.room.fetch(req('presence',{guestId:guest,tabId:tab}));assert.equal((await r.json()).online,1);r=await x.room.fetch(req('presence',{guestId:guest,tabId:tab+'2'}));assert.equal((await r.json()).online,1);for(const row of x.room.tabs.values())row.at=Date.now()-100000;r=await x.room.fetch(req('presence',{guestId:guest+'2',tabId:tab+'3'}));assert.equal((await r.json()).online,1);r=await x.room.fetch(req('presence',{guestId:guest+'2',tabId:tab+'3',leave:true}));assert.equal((await r.json()).online,0);assert.equal(x.writes(),w);assert.equal(x.reads(),0);x.db.close();});
test('same account on different tabs counts once and caches identity without D1 writes',async()=>{const x=setup();const cookie='vltk_cloud=abcdefghijklmnopqrstuv';for(const id of [tab,tab+'2']){const r=await x.room.fetch(req('presence',{guestId:guest,tabId:id},cookie));assert.equal((await r.json()).online,1)}assert.equal(x.reads(),1);x.db.close();});
test('chat moves to room SQLite, keeps recent history, rate limits spam and caches reads',async()=>{const x=setup();let r=await x.room.fetch(req('chat/session',{name:'Tester'}));assert.equal(r.status,200);const {token}=await r.json();const send=req('chat',{text:'Hello'});send.headers.set('authorization','Bearer '+token);r=await x.room.fetch(send);assert.equal(r.status,200);const {message}=await r.json();assert.equal(message.id,21);const again=req('chat',{text:'Again'});again.headers.set('authorization','Bearer '+token);assert.equal((await x.room.fetch(again)).status,429);r=await x.room.fetch(req('chat'));assert.deepEqual((await r.json()).messages.map(m=>m.text),['History','Hello']);const before=x.reads();await x.room.fetch(req('chat'));assert.equal(x.reads(),before);const w=x.writes();new SocialRoom(x.ctx,x.env);assert.equal(x.writes(),w);x.db.close();});
test('hibernated socket attachments preserve distinct online count and cannot send economic actions',()=>{const x=setup();function socket(){return {row:{actor:'account:same',at:Date.now(),chat:true},deserializeAttachment(){return this.row},serializeAttachment(row){this.row=row},send(text){this.sent=JSON.parse(text)},close(code){this.code=code}}}const a=socket(),b=socket();x.sockets.push(a,b);const w=x.writes();x.room.webSocketMessage(a,JSON.stringify({type:'heartbeat'}));assert.equal(a.sent.online,1);x.room.broadcast({id:1,text:'Test'});assert.equal(a.sent.type,'chat');const restored=new SocialRoom(x.ctx,x.env);assert.equal(restored.online(Date.now()),1);restored.webSocketMessage(a,JSON.stringify({type:'grant',gold:999999}));assert.equal(a.code,1008);restored.webSocketClose(b,1000);a.row.at=0;assert.equal(restored.online(Date.now()),0);assert.equal(x.writes(),w);x.db.close();});
test('presence rejects cross origin and malformed identities',async()=>{const x=setup(),r=req('presence',{guestId:'bad',tabId:tab});assert.equal((await x.room.fetch(r)).status,400);const cross=req('presence',{guestId:guest,tabId:tab});cross.headers.set('origin','https://evil.example');assert.equal((await x.room.fetch(cross)).status,403);x.db.close();});
test('social endpoints bypass D1 initialization even while D1 quota is exhausted',async()=>{let forwarded=0;const env={DB:{prepare(){throw Error('D1 quota exhausted')}},SOCIAL:{idFromName:name=>name,get(name){assert.equal(name,'global-v1');return {fetch:async r=>{forwarded++;return new Response(JSON.stringify({online:1}))}}}}};const r=await worker.fetch(req('presence',{guestId:guest,tabId:tab}),env,{});assert.equal(r.status,200);assert.equal(forwarded,1);});
